package com.gj.model;

import java.util.HashSet;
import java.util.Set;



/**
 * BswApplication generated by hbm2java
 */
public class BswApplication {

	private Integer idApplication;
	private String libelle;
	private Set<BswJournal> bswJournals = new HashSet<BswJournal>(0);

	public BswApplication() {
	}

	public BswApplication(String libelle, Set<BswJournal> bswJournals) {
		this.libelle = libelle;
		this.bswJournals = bswJournals;
	}

	public Integer getIdApplication() {
		return this.idApplication;
	}

	public void setIdApplication(Integer idApplication) {
		this.idApplication = idApplication;
	}

	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	public Set<BswJournal> getBswJournals() {
		return this.bswJournals;
	}

	public void setBswJournals(Set<BswJournal> bswJournals) {
		this.bswJournals = bswJournals;
	}

}
