package com.gj.model;

/**
 * BswAnnonce generated by hbm2java
 */
public class BswAnnonce  {

	private Integer idAnnonce;
	private String numeroBonCommande;
	private String coordonneeAnnonceur;
	private String codeSupport;

	public BswAnnonce() {
	}

	public BswAnnonce(String numeroBonCommande, String coordonneeAnnonceur,
			String codeSupport) {
		this.numeroBonCommande = numeroBonCommande;
		this.coordonneeAnnonceur = coordonneeAnnonceur;
		this.codeSupport = codeSupport;
	}

	public Integer getIdAnnonce() {
		return this.idAnnonce;
	}

	public void setIdAnnonce(Integer idAnnonce) {
		this.idAnnonce = idAnnonce;
	}

	public String getNumeroBonCommande() {
		return this.numeroBonCommande;
	}

	public void setNumeroBonCommande(String numeroBonCommande) {
		this.numeroBonCommande = numeroBonCommande;
	}

	public String getCoordonneeAnnonceur() {
		return this.coordonneeAnnonceur;
	}

	public void setCoordonneeAnnonceur(String coordonneeAnnonceur) {
		this.coordonneeAnnonceur = coordonneeAnnonceur;
	}

	public String getCodeSupport() {
		return this.codeSupport;
	}

	public void setCodeSupport(String codeSupport) {
		this.codeSupport = codeSupport;
	}

}
