package com.gj.model;

// Generated 4 mars 2014 09:23:20 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;

import org.codehaus.jackson.annotate.JsonIgnore;
import org.codehaus.jackson.map.annotate.JsonView;

/**
 * BswCoordonnee generated by hbm2java
 */
public class BswCoordonnee implements Serializable {
	
	@JsonView
	private Integer idCoordonnee;
	@JsonIgnore
	private BswPays bswPays;
	@JsonIgnore
	private BswUnitorg bswUnitorg;
	@JsonIgnore
	private BswPersonne bswPersonne;
	@JsonView
	private Integer idPortalEntity;
	@JsonView
	private String libelle;
	@JsonView
	private String tel;
	@JsonView
	private String fax;
	@JsonView
	private String mobile;
	@JsonView
	private String email;
	@JsonView
	private String siteWeb;
	@JsonView
	private String typeAdressePostale;
	@JsonView
	private String destinataire;
	@JsonView
	private String destinataireComplement;
	@JsonView
	private String adresseLigne1;
	@JsonView
	private String numeroVoie;
	@JsonView
	private String libelleVoie;
	@JsonView
	private String adresseLigne3;
	@JsonView
	private String codePostal;
	@JsonView
	private String ville;
	@JsonView
	private String cedex;
	@JsonView
	private boolean defaut;

	public BswCoordonnee() {
	}

	public BswCoordonnee(boolean defaut) {
		this.defaut = defaut;
	}

	public BswCoordonnee(BswPays bswPays, BswUnitorg bswUnitorg,
			BswPersonne bswPersonne, Integer idPortalEntity, String libelle,
			String tel, String fax, String mobile, String email,
			String siteWeb, String typeAdressePostale, String destinataire,
			String destinataireComplement, String adresseLigne1,
			String numeroVoie, String libelleVoie, String adresseLigne3,
			String codePostal, String ville, String cedex, boolean defaut) {
		this.bswPays = bswPays;
		this.bswUnitorg = bswUnitorg;
		this.bswPersonne = bswPersonne;
		this.idPortalEntity = idPortalEntity;
		this.libelle = libelle;
		this.tel = tel;
		this.fax = fax;
		this.mobile = mobile;
		this.email = email;
		this.siteWeb = siteWeb;
		this.typeAdressePostale = typeAdressePostale;
		this.destinataire = destinataire;
		this.destinataireComplement = destinataireComplement;
		this.adresseLigne1 = adresseLigne1;
		this.numeroVoie = numeroVoie;
		this.libelleVoie = libelleVoie;
		this.adresseLigne3 = adresseLigne3;
		this.codePostal = codePostal;
		this.ville = ville;
		this.cedex = cedex;
		this.defaut = defaut;
	}

	public Integer getIdCoordonnee() {
		return this.idCoordonnee;
	}

	public void setIdCoordonnee(Integer idCoordonnee) {
		this.idCoordonnee = idCoordonnee;
	}

	public BswPays getBswPays() {
		return this.bswPays;
	}

	public void setBswPays(BswPays bswPays) {
		this.bswPays = bswPays;
	}

	public BswUnitorg getBswUnitorg() {
		return this.bswUnitorg;
	}

	public void setBswUnitorg(BswUnitorg bswUnitorg) {
		this.bswUnitorg = bswUnitorg;
	}

	public BswPersonne getBswPersonne() {
		return this.bswPersonne;
	}

	public void setBswPersonne(BswPersonne bswPersonne) {
		this.bswPersonne = bswPersonne;
	}

	public Integer getIdPortalEntity() {
		return this.idPortalEntity;
	}

	public void setIdPortalEntity(Integer idPortalEntity) {
		this.idPortalEntity = idPortalEntity;
	}

	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getSiteWeb() {
		return this.siteWeb;
	}

	public void setSiteWeb(String siteWeb) {
		this.siteWeb = siteWeb;
	}

	public String getTypeAdressePostale() {
		return this.typeAdressePostale;
	}

	public void setTypeAdressePostale(String typeAdressePostale) {
		this.typeAdressePostale = typeAdressePostale;
	}

	public String getDestinataire() {
		return this.destinataire;
	}

	public void setDestinataire(String destinataire) {
		this.destinataire = destinataire;
	}

	public String getDestinataireComplement() {
		return this.destinataireComplement;
	}

	public void setDestinataireComplement(String destinataireComplement) {
		this.destinataireComplement = destinataireComplement;
	}

	public String getAdresseLigne1() {
		return this.adresseLigne1;
	}

	public void setAdresseLigne1(String adresseLigne1) {
		this.adresseLigne1 = adresseLigne1;
	}

	public String getNumeroVoie() {
		return this.numeroVoie;
	}

	public void setNumeroVoie(String numeroVoie) {
		this.numeroVoie = numeroVoie;
	}

	public String getLibelleVoie() {
		return this.libelleVoie;
	}

	public void setLibelleVoie(String libelleVoie) {
		this.libelleVoie = libelleVoie;
	}

	public String getAdresseLigne3() {
		return this.adresseLigne3;
	}

	public void setAdresseLigne3(String adresseLigne3) {
		this.adresseLigne3 = adresseLigne3;
	}

	public String getCodePostal() {
		return this.codePostal;
	}

	public void setCodePostal(String codePostal) {
		this.codePostal = codePostal;
	}

	public String getVille() {
		return this.ville;
	}

	public void setVille(String ville) {
		this.ville = ville;
	}

	public String getCedex() {
		return this.cedex;
	}

	public void setCedex(String cedex) {
		this.cedex = cedex;
	}

	public boolean isDefaut() {
		return this.defaut;
	}

	public void setDefaut(boolean defaut) {
		this.defaut = defaut;
	}

}
