package com.gj.model;
/**
 * BswCommune generated by hbm2java
 */
public class BswCommune   {

	private Integer idCommune;
	private String libelle;

	public BswCommune() {
	}

	public BswCommune(String libelle) {
		this.libelle = libelle;
	}

	public Integer getIdCommune() {
		return this.idCommune;
	}

	public void setIdCommune(Integer idCommune) {
		this.idCommune = idCommune;
	}

	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

}
