package com.gj.model;

// Generated 4 mars 2014 09:23:20 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;


/**
 * BswdtContenuImage generated by hbm2java
 */
public class BswdtContenuImage  {

	private Integer idContenuImage;
	private String titre;
	private String credit;
	private String legende;
	private String urlImage;
	private String urlVignette;
	private String info;
	private Set<BswdtUniteRedactionnelle> bswdtUniteRedactionnelles = new HashSet<BswdtUniteRedactionnelle>(
			0);

	public BswdtContenuImage() {
	}

	public BswdtContenuImage(String titre, String credit, String legende,
			String urlImage, String urlVignette, String info,
			Set<BswdtUniteRedactionnelle> bswdtUniteRedactionnelles) {
		this.titre = titre;
		this.credit = credit;
		this.legende = legende;
		this.urlImage = urlImage;
		this.urlVignette = urlVignette;
		this.info = info;
		this.bswdtUniteRedactionnelles = bswdtUniteRedactionnelles;
	}

	public Integer getIdContenuImage() {
		return this.idContenuImage;
	}

	public void setIdContenuImage(Integer idContenuImage) {
		this.idContenuImage = idContenuImage;
	}

	public String getTitre() {
		return this.titre;
	}

	public void setTitre(String titre) {
		this.titre = titre;
	}

	public String getCredit() {
		return this.credit;
	}

	public void setCredit(String credit) {
		this.credit = credit;
	}

	public String getLegende() {
		return this.legende;
	}

	public void setLegende(String legende) {
		this.legende = legende;
	}

	public String getUrlImage() {
		return this.urlImage;
	}

	public void setUrlImage(String urlImage) {
		this.urlImage = urlImage;
	}

	public String getUrlVignette() {
		return this.urlVignette;
	}

	public void setUrlVignette(String urlVignette) {
		this.urlVignette = urlVignette;
	}

	public String getInfo() {
		return this.info;
	}

	public void setInfo(String info) {
		this.info = info;
	}

	public Set<BswdtUniteRedactionnelle> getBswdtUniteRedactionnelles() {
		return this.bswdtUniteRedactionnelles;
	}

	public void setBswdtUniteRedactionnelles(
			Set<BswdtUniteRedactionnelle> bswdtUniteRedactionnelles) {
		this.bswdtUniteRedactionnelles = bswdtUniteRedactionnelles;
	}

}
