package com.gj.model;

// Generated 4 mars 2014 09:23:20 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;



/**
 * BswdtRubrique generated by hbm2java
 */
public class BswdtRubrique  {

	private Integer idRubrique;
	private String libelle;
	private Set<BswdtPage> bswdtPages = new HashSet<BswdtPage>(0);

	public BswdtRubrique() {
	}

	public BswdtRubrique(String libelle, Set<BswdtPage> bswdtPages) {
		this.libelle = libelle;
		this.bswdtPages = bswdtPages;
	}

	public Integer getIdRubrique() {
		return this.idRubrique;
	}

	public void setIdRubrique(Integer idRubrique) {
		this.idRubrique = idRubrique;
	}

	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	public Set<BswdtPage> getBswdtPages() {
		return this.bswdtPages;
	}

	public void setBswdtPages(Set<BswdtPage> bswdtPages) {
		this.bswdtPages = bswdtPages;
	}

}
