package com.gj.model;

import java.util.HashSet;
import java.util.Set;



/**
 * BswDepartement generated by hbm2java
 */
public class BswDepartement   {

	private Integer idDepartement;
	private String libelle;
	private Set<BswJournal> bswJournals = new HashSet<BswJournal>(0);

	public BswDepartement() {
	}

	public BswDepartement(String libelle, Set<BswJournal> bswJournals) {
		this.libelle = libelle;
		this.bswJournals = bswJournals;
	}

	public Integer getIdDepartement() {
		return this.idDepartement;
	}

	public void setIdDepartement(Integer idDepartement) {
		this.idDepartement = idDepartement;
	}

	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	public Set<BswJournal> getBswJournals() {
		return this.bswJournals;
	}

	public void setBswJournals(Set<BswJournal> bswJournals) {
		this.bswJournals = bswJournals;
	}

}
