package com.gj.model;

// Generated 4 mars 2014 09:23:20 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;



/**
 * BswdtPage generated by hbm2java
 */
public class BswdtPage   {

	private Integer idPage;
	private BswParution bswParution;
	private BswJournal bswJournal;
	private BswdtModelPage bswdtModelPage;
	private String libelle;
	private Integer numeroPage;
	private boolean locked;
	private Set<BswdtRubrique> bswdtRubriques = new HashSet<BswdtRubrique>(0);
	private Set<BswdtUniteRedactionnelle> bswdtUniteRedactionnelles = new HashSet<BswdtUniteRedactionnelle>(
			0);
	private Set<BswPersonne> bswPersonnes = new HashSet<BswPersonne>(0);

	public BswdtPage() {
	}

	public BswdtPage(boolean locked) {
		this.locked = locked;
	}

	public BswdtPage(BswParution bswParution, BswJournal bswJournal,
			BswdtModelPage bswdtModelPage, String libelle, Integer numeroPage,
			boolean locked, Set<BswdtRubrique> bswdtRubriques,
			Set<BswdtUniteRedactionnelle> bswdtUniteRedactionnelles,
			Set<BswPersonne> bswPersonnes) {
		this.bswParution = bswParution;
		this.bswJournal = bswJournal;
		this.bswdtModelPage = bswdtModelPage;
		this.libelle = libelle;
		this.numeroPage = numeroPage;
		this.locked = locked;
		this.bswdtRubriques = bswdtRubriques;
		this.bswdtUniteRedactionnelles = bswdtUniteRedactionnelles;
		this.bswPersonnes = bswPersonnes;
	}

	public Integer getIdPage() {
		return this.idPage;
	}

	public void setIdPage(Integer idPage) {
		this.idPage = idPage;
	}

	public BswParution getBswParution() {
		return this.bswParution;
	}

	public void setBswParution(BswParution bswParution) {
		this.bswParution = bswParution;
	}

	public BswJournal getBswJournal() {
		return this.bswJournal;
	}

	public void setBswJournal(BswJournal bswJournal) {
		this.bswJournal = bswJournal;
	}

	public BswdtModelPage getBswdtModelPage() {
		return this.bswdtModelPage;
	}

	public void setBswdtModelPage(BswdtModelPage bswdtModelPage) {
		this.bswdtModelPage = bswdtModelPage;
	}

	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	public Integer getNumeroPage() {
		return this.numeroPage;
	}

	public void setNumeroPage(Integer numeroPage) {
		this.numeroPage = numeroPage;
	}

	public boolean isLocked() {
		return this.locked;
	}

	public void setLocked(boolean locked) {
		this.locked = locked;
	}

	public Set<BswdtRubrique> getBswdtRubriques() {
		return this.bswdtRubriques;
	}

	public void setBswdtRubriques(Set<BswdtRubrique> bswdtRubriques) {
		this.bswdtRubriques = bswdtRubriques;
	}

	public Set<BswdtUniteRedactionnelle> getBswdtUniteRedactionnelles() {
		return this.bswdtUniteRedactionnelles;
	}

	public void setBswdtUniteRedactionnelles(
			Set<BswdtUniteRedactionnelle> bswdtUniteRedactionnelles) {
		this.bswdtUniteRedactionnelles = bswdtUniteRedactionnelles;
	}

	public Set<BswPersonne> getBswPersonnes() {
		return this.bswPersonnes;
	}

	public void setBswPersonnes(Set<BswPersonne> bswPersonnes) {
		this.bswPersonnes = bswPersonnes;
	}

}
