package com.gj.model;

// Generated 4 mars 2014 09:23:20 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;


/**
 * BswdtContenuTexte generated by hbm2java
 */
public class BswdtContenuTexte   {

	private Integer idContenuTexte;
	private String titre;
	private String texte;
	private String chapo;
	private String exergue;
	private String surTitre;
	private String source;
	private String encadrerUn;
	private String encadrerDeux;
	private String encadrerTrois;
	private String encadrerQuatre;
	private Set<BswdtUniteRedactionnelle> bswdtUniteRedactionnelles = new HashSet<BswdtUniteRedactionnelle>(
			0);

	public BswdtContenuTexte() {
	}

	public BswdtContenuTexte(String titre, String texte, String chapo,
			String exergue, String surTitre, String source, String encadrerUn,
			String encadrerDeux, String encadrerTrois, String encadrerQuatre,
			Set<BswdtUniteRedactionnelle> bswdtUniteRedactionnelles) {
		this.titre = titre;
		this.texte = texte;
		this.chapo = chapo;
		this.exergue = exergue;
		this.surTitre = surTitre;
		this.source = source;
		this.encadrerUn = encadrerUn;
		this.encadrerDeux = encadrerDeux;
		this.encadrerTrois = encadrerTrois;
		this.encadrerQuatre = encadrerQuatre;
		this.bswdtUniteRedactionnelles = bswdtUniteRedactionnelles;
	}

	public Integer getIdContenuTexte() {
		return this.idContenuTexte;
	}

	public void setIdContenuTexte(Integer idContenuTexte) {
		this.idContenuTexte = idContenuTexte;
	}

	public String getTitre() {
		return this.titre;
	}

	public void setTitre(String titre) {
		this.titre = titre;
	}

	public String getTexte() {
		return this.texte;
	}

	public void setTexte(String texte) {
		this.texte = texte;
	}

	public String getChapo() {
		return this.chapo;
	}

	public void setChapo(String chapo) {
		this.chapo = chapo;
	}

	public String getExergue() {
		return this.exergue;
	}

	public void setExergue(String exergue) {
		this.exergue = exergue;
	}

	public String getSurTitre() {
		return this.surTitre;
	}

	public void setSurTitre(String surTitre) {
		this.surTitre = surTitre;
	}

	public String getSource() {
		return this.source;
	}

	public void setSource(String source) {
		this.source = source;
	}

	public String getEncadrerUn() {
		return this.encadrerUn;
	}

	public void setEncadrerUn(String encadrerUn) {
		this.encadrerUn = encadrerUn;
	}

	public String getEncadrerDeux() {
		return this.encadrerDeux;
	}

	public void setEncadrerDeux(String encadrerDeux) {
		this.encadrerDeux = encadrerDeux;
	}

	public String getEncadrerTrois() {
		return this.encadrerTrois;
	}

	public void setEncadrerTrois(String encadrerTrois) {
		this.encadrerTrois = encadrerTrois;
	}

	public String getEncadrerQuatre() {
		return this.encadrerQuatre;
	}

	public void setEncadrerQuatre(String encadrerQuatre) {
		this.encadrerQuatre = encadrerQuatre;
	}

	public Set<BswdtUniteRedactionnelle> getBswdtUniteRedactionnelles() {
		return this.bswdtUniteRedactionnelles;
	}

	public void setBswdtUniteRedactionnelles(
			Set<BswdtUniteRedactionnelle> bswdtUniteRedactionnelles) {
		this.bswdtUniteRedactionnelles = bswdtUniteRedactionnelles;
	}

}
