package com.gj.model;

// Generated 4 mars 2014 09:23:20 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * BswdtUniteRedactionnelle generated by hbm2java
 */
public class BswdtUniteRedactionnelle  {

	private Integer idUniteRedactionnelle;
	private BswdtContenuTexte bswdtContenuTexte;
	private BswdtContenuImage bswdtContenuImage;
	private BswPersonne bswPersonne;
	private BswdtUniteRedactionnelleDefinition bswdtUniteRedactionnelleDefinition;
	private BswdtPage bswdtPage;
	private BswdtContenuFichier bswdtContenuFichier;
	private String numero;
	private String sujet;
	private String reference;
	private Boolean miseEnPage;
	private String commentaire;
	private Date dateLimiteDepot;
	private String statut;
	private Date dateCreation;
	private Date dateModification;
	private String auteurCreation;
	private String auteurModification;
	private boolean publiSiteGene;
	private boolean verrouillage;
	private String emailVerrouilleur;
	private Date dateVerrouillage;
	private Set<BswdtForum> bswdtForums = new HashSet<BswdtForum>(0);

	public BswdtUniteRedactionnelle() {
	}

	public BswdtUniteRedactionnelle(boolean publiSiteGene, boolean verrouillage) {
		this.publiSiteGene = publiSiteGene;
		this.verrouillage = verrouillage;
	}

	public BswdtUniteRedactionnelle(
			BswdtContenuTexte bswdtContenuTexte,
			BswdtContenuImage bswdtContenuImage,
			BswPersonne bswPersonne,
			BswdtUniteRedactionnelleDefinition bswdtUniteRedactionnelleDefinition,
			BswdtPage bswdtPage, BswdtContenuFichier bswdtContenuFichier,
			String numero, String sujet, String reference, Boolean miseEnPage,
			String commentaire, Date dateLimiteDepot, String statut,
			Date dateCreation, Date dateModification, String auteurCreation,
			String auteurModification, boolean publiSiteGene,
			boolean verrouillage, String emailVerrouilleur,
			Date dateVerrouillage, Set<BswdtForum> bswdtForums) {
		this.bswdtContenuTexte = bswdtContenuTexte;
		this.bswdtContenuImage = bswdtContenuImage;
		this.bswPersonne = bswPersonne;
		this.bswdtUniteRedactionnelleDefinition = bswdtUniteRedactionnelleDefinition;
		this.bswdtPage = bswdtPage;
		this.bswdtContenuFichier = bswdtContenuFichier;
		this.numero = numero;
		this.sujet = sujet;
		this.reference = reference;
		this.miseEnPage = miseEnPage;
		this.commentaire = commentaire;
		this.dateLimiteDepot = dateLimiteDepot;
		this.statut = statut;
		this.dateCreation = dateCreation;
		this.dateModification = dateModification;
		this.auteurCreation = auteurCreation;
		this.auteurModification = auteurModification;
		this.publiSiteGene = publiSiteGene;
		this.verrouillage = verrouillage;
		this.emailVerrouilleur = emailVerrouilleur;
		this.dateVerrouillage = dateVerrouillage;
		this.bswdtForums = bswdtForums;
	}

	public Integer getIdUniteRedactionnelle() {
		return this.idUniteRedactionnelle;
	}

	public void setIdUniteRedactionnelle(Integer idUniteRedactionnelle) {
		this.idUniteRedactionnelle = idUniteRedactionnelle;
	}

	public BswdtContenuTexte getBswdtContenuTexte() {
		return this.bswdtContenuTexte;
	}

	public void setBswdtContenuTexte(BswdtContenuTexte bswdtContenuTexte) {
		this.bswdtContenuTexte = bswdtContenuTexte;
	}

	public BswdtContenuImage getBswdtContenuImage() {
		return this.bswdtContenuImage;
	}

	public void setBswdtContenuImage(BswdtContenuImage bswdtContenuImage) {
		this.bswdtContenuImage = bswdtContenuImage;
	}

	public BswPersonne getBswPersonne() {
		return this.bswPersonne;
	}

	public void setBswPersonne(BswPersonne bswPersonne) {
		this.bswPersonne = bswPersonne;
	}

	public BswdtUniteRedactionnelleDefinition getBswdtUniteRedactionnelleDefinition() {
		return this.bswdtUniteRedactionnelleDefinition;
	}

	public void setBswdtUniteRedactionnelleDefinition(
			BswdtUniteRedactionnelleDefinition bswdtUniteRedactionnelleDefinition) {
		this.bswdtUniteRedactionnelleDefinition = bswdtUniteRedactionnelleDefinition;
	}

	public BswdtPage getBswdtPage() {
		return this.bswdtPage;
	}

	public void setBswdtPage(BswdtPage bswdtPage) {
		this.bswdtPage = bswdtPage;
	}

	public BswdtContenuFichier getBswdtContenuFichier() {
		return this.bswdtContenuFichier;
	}

	public void setBswdtContenuFichier(BswdtContenuFichier bswdtContenuFichier) {
		this.bswdtContenuFichier = bswdtContenuFichier;
	}

	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	public String getSujet() {
		return this.sujet;
	}

	public void setSujet(String sujet) {
		this.sujet = sujet;
	}

	public String getReference() {
		return this.reference;
	}

	public void setReference(String reference) {
		this.reference = reference;
	}

	public Boolean getMiseEnPage() {
		return this.miseEnPage;
	}

	public void setMiseEnPage(Boolean miseEnPage) {
		this.miseEnPage = miseEnPage;
	}

	public String getCommentaire() {
		return this.commentaire;
	}

	public void setCommentaire(String commentaire) {
		this.commentaire = commentaire;
	}

	public Date getDateLimiteDepot() {
		return this.dateLimiteDepot;
	}

	public void setDateLimiteDepot(Date dateLimiteDepot) {
		this.dateLimiteDepot = dateLimiteDepot;
	}

	public String getStatut() {
		return this.statut;
	}

	public void setStatut(String statut) {
		this.statut = statut;
	}

	public Date getDateCreation() {
		return this.dateCreation;
	}

	public void setDateCreation(Date dateCreation) {
		this.dateCreation = dateCreation;
	}

	public Date getDateModification() {
		return this.dateModification;
	}

	public void setDateModification(Date dateModification) {
		this.dateModification = dateModification;
	}

	public String getAuteurCreation() {
		return this.auteurCreation;
	}

	public void setAuteurCreation(String auteurCreation) {
		this.auteurCreation = auteurCreation;
	}

	public String getAuteurModification() {
		return this.auteurModification;
	}

	public void setAuteurModification(String auteurModification) {
		this.auteurModification = auteurModification;
	}

	public boolean isPubliSiteGene() {
		return this.publiSiteGene;
	}

	public void setPubliSiteGene(boolean publiSiteGene) {
		this.publiSiteGene = publiSiteGene;
	}

	public boolean isVerrouillage() {
		return this.verrouillage;
	}

	public void setVerrouillage(boolean verrouillage) {
		this.verrouillage = verrouillage;
	}

	public String getEmailVerrouilleur() {
		return this.emailVerrouilleur;
	}

	public void setEmailVerrouilleur(String emailVerrouilleur) {
		this.emailVerrouilleur = emailVerrouilleur;
	}

	public Date getDateVerrouillage() {
		return this.dateVerrouillage;
	}

	public void setDateVerrouillage(Date dateVerrouillage) {
		this.dateVerrouillage = dateVerrouillage;
	}

	public Set<BswdtForum> getBswdtForums() {
		return this.bswdtForums;
	}

	public void setBswdtForums(Set<BswdtForum> bswdtForums) {
		this.bswdtForums = bswdtForums;
	}

}
