package com.gj.model;

// Generated 4 mars 2014 09:23:20 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;


/**
 * BswdtModelPage generated by hbm2java
 */
public class BswdtModelPage   {

	private Integer idModelPage;
	private String libelle;
	private Boolean modifiable;
	private String imageSnapshot;
	private String image;
	private Set<BswdtPage> bswdtPages = new HashSet<BswdtPage>(0);
	private Set<BswJournal> bswJournals = new HashSet<BswJournal>(0);
	private Set<BswdtUniteRedactionnelleDefinition> bswdtUniteRedactionnelleDefinitions = new HashSet<BswdtUniteRedactionnelleDefinition>(
			0);

	public BswdtModelPage() {
	}

	public BswdtModelPage(
			String libelle,
			Boolean modifiable,
			String imageSnapshot,
			String image,
			Set<BswdtPage> bswdtPages,
			Set<BswJournal> bswJournals,
			Set<BswdtUniteRedactionnelleDefinition> bswdtUniteRedactionnelleDefinitions) {
		this.libelle = libelle;
		this.modifiable = modifiable;
		this.imageSnapshot = imageSnapshot;
		this.image = image;
		this.bswdtPages = bswdtPages;
		this.bswJournals = bswJournals;
		this.bswdtUniteRedactionnelleDefinitions = bswdtUniteRedactionnelleDefinitions;
	}

	public Integer getIdModelPage() {
		return this.idModelPage;
	}

	public void setIdModelPage(Integer idModelPage) {
		this.idModelPage = idModelPage;
	}

	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	public Boolean getModifiable() {
		return this.modifiable;
	}

	public void setModifiable(Boolean modifiable) {
		this.modifiable = modifiable;
	}

	public String getImageSnapshot() {
		return this.imageSnapshot;
	}

	public void setImageSnapshot(String imageSnapshot) {
		this.imageSnapshot = imageSnapshot;
	}

	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	public Set<BswdtPage> getBswdtPages() {
		return this.bswdtPages;
	}

	public void setBswdtPages(Set<BswdtPage> bswdtPages) {
		this.bswdtPages = bswdtPages;
	}

	public Set<BswJournal> getBswJournals() {
		return this.bswJournals;
	}

	public void setBswJournals(Set<BswJournal> bswJournals) {
		this.bswJournals = bswJournals;
	}

	public Set<BswdtUniteRedactionnelleDefinition> getBswdtUniteRedactionnelleDefinitions() {
		return this.bswdtUniteRedactionnelleDefinitions;
	}

	public void setBswdtUniteRedactionnelleDefinitions(
			Set<BswdtUniteRedactionnelleDefinition> bswdtUniteRedactionnelleDefinitions) {
		this.bswdtUniteRedactionnelleDefinitions = bswdtUniteRedactionnelleDefinitions;
	}

}
