package com.gj.model;

// Generated 4 mars 2014 09:23:20 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;



/**
 * BswdtForum generated by hbm2java
 */
public class BswdtForum   {

	private Integer idForum;
	private BswdtForum bswdtForum;
	private BswPersonne bswPersonne;
	private BswdtUniteRedactionnelle bswdtUniteRedactionnelle;
	private String sujet;
	private String texte;
	private Long time;
	private Boolean visibleRedacteur;
	private Set<BswdtForum> bswdtForums = new HashSet<BswdtForum>(0);

	public BswdtForum() {
	}

	public BswdtForum(BswdtForum bswdtForum, BswPersonne bswPersonne,
			BswdtUniteRedactionnelle bswdtUniteRedactionnelle, String sujet,
			String texte, Long time, Boolean visibleRedacteur,
			Set<BswdtForum> bswdtForums) {
		this.bswdtForum = bswdtForum;
		this.bswPersonne = bswPersonne;
		this.bswdtUniteRedactionnelle = bswdtUniteRedactionnelle;
		this.sujet = sujet;
		this.texte = texte;
		this.time = time;
		this.visibleRedacteur = visibleRedacteur;
		this.bswdtForums = bswdtForums;
	}

	public Integer getIdForum() {
		return this.idForum;
	}

	public void setIdForum(Integer idForum) {
		this.idForum = idForum;
	}

	public BswdtForum getBswdtForum() {
		return this.bswdtForum;
	}

	public void setBswdtForum(BswdtForum bswdtForum) {
		this.bswdtForum = bswdtForum;
	}

	public BswPersonne getBswPersonne() {
		return this.bswPersonne;
	}

	public void setBswPersonne(BswPersonne bswPersonne) {
		this.bswPersonne = bswPersonne;
	}

	public BswdtUniteRedactionnelle getBswdtUniteRedactionnelle() {
		return this.bswdtUniteRedactionnelle;
	}

	public void setBswdtUniteRedactionnelle(
			BswdtUniteRedactionnelle bswdtUniteRedactionnelle) {
		this.bswdtUniteRedactionnelle = bswdtUniteRedactionnelle;
	}

	public String getSujet() {
		return this.sujet;
	}

	public void setSujet(String sujet) {
		this.sujet = sujet;
	}

	public String getTexte() {
		return this.texte;
	}

	public void setTexte(String texte) {
		this.texte = texte;
	}

	public Long getTime() {
		return this.time;
	}

	public void setTime(Long time) {
		this.time = time;
	}

	public Boolean getVisibleRedacteur() {
		return this.visibleRedacteur;
	}

	public void setVisibleRedacteur(Boolean visibleRedacteur) {
		this.visibleRedacteur = visibleRedacteur;
	}

	public Set<BswdtForum> getBswdtForums() {
		return this.bswdtForums;
	}

	public void setBswdtForums(Set<BswdtForum> bswdtForums) {
		this.bswdtForums = bswdtForums;
	}

}
