package com.gj.model;

import java.util.Date;


/**
 * BswdfFichier generated by hbm2java
 */
public class BswdfFichier  {

	private Integer idFichier;
	private BswParution bswParution;
	private String filename;
	private String noPage;
	private int statut;
	private String auteurDepot;
	private Date dateDepot;
	private String auteurDerniereAction;
	private Date dateDerniereAction;

	public BswdfFichier() {
	}

	public BswdfFichier(BswParution bswParution, String filename,
			String noPage, int statut, String auteurDepot, Date dateDepot,
			String auteurDerniereAction, Date dateDerniereAction) {
		this.bswParution = bswParution;
		this.filename = filename;
		this.noPage = noPage;
		this.statut = statut;
		this.auteurDepot = auteurDepot;
		this.dateDepot = dateDepot;
		this.auteurDerniereAction = auteurDerniereAction;
		this.dateDerniereAction = dateDerniereAction;
	}

	public Integer getIdFichier() {
		return this.idFichier;
	}

	public void setIdFichier(Integer idFichier) {
		this.idFichier = idFichier;
	}

	public BswParution getBswParution() {
		return this.bswParution;
	}

	public void setBswParution(BswParution bswParution) {
		this.bswParution = bswParution;
	}

	public String getFilename() {
		return this.filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

	public String getNoPage() {
		return this.noPage;
	}

	public void setNoPage(String noPage) {
		this.noPage = noPage;
	}

	public int getStatut() {
		return this.statut;
	}

	public void setStatut(int statut) {
		this.statut = statut;
	}

	public String getAuteurDepot() {
		return this.auteurDepot;
	}

	public void setAuteurDepot(String auteurDepot) {
		this.auteurDepot = auteurDepot;
	}

	public Date getDateDepot() {
		return this.dateDepot;
	}

	public void setDateDepot(Date dateDepot) {
		this.dateDepot = dateDepot;
	}

	public String getAuteurDerniereAction() {
		return this.auteurDerniereAction;
	}

	public void setAuteurDerniereAction(String auteurDerniereAction) {
		this.auteurDerniereAction = auteurDerniereAction;
	}

	public Date getDateDerniereAction() {
		return this.dateDerniereAction;
	}

	public void setDateDerniereAction(Date dateDerniereAction) {
		this.dateDerniereAction = dateDerniereAction;
	}

}
