package com.gj.model;

// Generated 4 mars 2014 09:23:20 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;


/**
 * BswFamille generated by hbm2java
 */
public class BswFamille  {

	private Integer idFamille;
	private String nom;
	private Set<BswSousFamille> bswSousFamilles = new HashSet<BswSousFamille>(0);
	private Set<BswJournal> bswJournals = new HashSet<BswJournal>(0);

	public BswFamille() {
	}

	public BswFamille(String nom, Set<BswSousFamille> bswSousFamilles,
			Set<BswJournal> bswJournals) {
		this.nom = nom;
		this.bswSousFamilles = bswSousFamilles;
		this.bswJournals = bswJournals;
	}

	public Integer getIdFamille() {
		return this.idFamille;
	}

	public void setIdFamille(Integer idFamille) {
		this.idFamille = idFamille;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public Set<BswSousFamille> getBswSousFamilles() {
		return this.bswSousFamilles;
	}

	public void setBswSousFamilles(Set<BswSousFamille> bswSousFamilles) {
		this.bswSousFamilles = bswSousFamilles;
	}

	public Set<BswJournal> getBswJournals() {
		return this.bswJournals;
	}

	public void setBswJournals(Set<BswJournal> bswJournals) {
		this.bswJournals = bswJournals;
	}

}
