package com.gj.model;

// Generated 4 mars 2014 09:23:20 by Hibernate Tools 3.4.0.CR1

import java.util.Date;


/**
 * BswFonction generated by hbm2java
 */
public class BswFonction   {

	private Integer idFonction;
	private BswPersonne bswPersonne;
	private BswUnitorg bswUnitorg;
	private BswLabelFonction bswLabelFonction;
	private String commentaire;
	private Date dateDebut;
	private Date dateFin;

	public BswFonction() {
	}

	public BswFonction(BswPersonne bswPersonne, BswUnitorg bswUnitorg,
			BswLabelFonction bswLabelFonction, String commentaire,
			Date dateDebut, Date dateFin) {
		this.bswPersonne = bswPersonne;
		this.bswUnitorg = bswUnitorg;
		this.bswLabelFonction = bswLabelFonction;
		this.commentaire = commentaire;
		this.dateDebut = dateDebut;
		this.dateFin = dateFin;
	}

	public Integer getIdFonction() {
		return this.idFonction;
	}

	public void setIdFonction(Integer idFonction) {
		this.idFonction = idFonction;
	}

	public BswPersonne getBswPersonne() {
		return this.bswPersonne;
	}

	public void setBswPersonne(BswPersonne bswPersonne) {
		this.bswPersonne = bswPersonne;
	}

	public BswUnitorg getBswUnitorg() {
		return this.bswUnitorg;
	}

	public void setBswUnitorg(BswUnitorg bswUnitorg) {
		this.bswUnitorg = bswUnitorg;
	}

	public BswLabelFonction getBswLabelFonction() {
		return this.bswLabelFonction;
	}

	public void setBswLabelFonction(BswLabelFonction bswLabelFonction) {
		this.bswLabelFonction = bswLabelFonction;
	}

	public String getCommentaire() {
		return this.commentaire;
	}

	public void setCommentaire(String commentaire) {
		this.commentaire = commentaire;
	}

	public Date getDateDebut() {
		return this.dateDebut;
	}

	public void setDateDebut(Date dateDebut) {
		this.dateDebut = dateDebut;
	}

	public Date getDateFin() {
		return this.dateFin;
	}

	public void setDateFin(Date dateFin) {
		this.dateFin = dateFin;
	}

}
