package com.gj.model;



// Generated 4 mars 2014 09:23:20 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;


/**
 * BswgaSecteur generated by hbm2java
 */
public class BswgaSecteur   {

	private Integer idSecteur;
	private BswJournal bswJournal;
	private String nom;
	private boolean defaut;
	private Set<BswPersonne> bswPersonnes = new HashSet<BswPersonne>(0);
	private Set<BswPersonne> bswPersonnes_1 = new HashSet<BswPersonne>(0);
	private Set<BswgaJournalHasAbonne> bswgaJournalHasAbonnes = new HashSet<BswgaJournalHasAbonne>(
			0);

	public BswgaSecteur() {
	}

	public BswgaSecteur(boolean defaut) {
		this.defaut = defaut;
	}

	public BswgaSecteur(BswJournal bswJournal, String nom, boolean defaut,
			Set<BswPersonne> bswPersonnes, Set<BswPersonne> bswPersonnes_1,
			Set<BswgaJournalHasAbonne> bswgaJournalHasAbonnes) {
		this.bswJournal = bswJournal;
		this.nom = nom;
		this.defaut = defaut;
		this.bswPersonnes = bswPersonnes;
		this.bswPersonnes_1 = bswPersonnes_1;
		this.bswgaJournalHasAbonnes = bswgaJournalHasAbonnes;
	}

	public Integer getIdSecteur() {
		return this.idSecteur;
	}

	public void setIdSecteur(Integer idSecteur) {
		this.idSecteur = idSecteur;
	}

	public BswJournal getBswJournal() {
		return this.bswJournal;
	}

	public void setBswJournal(BswJournal bswJournal) {
		this.bswJournal = bswJournal;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public boolean isDefaut() {
		return this.defaut;
	}

	public void setDefaut(boolean defaut) {
		this.defaut = defaut;
	}

	public Set<BswPersonne> getBswPersonnes() {
		return this.bswPersonnes;
	}

	public void setBswPersonnes(Set<BswPersonne> bswPersonnes) {
		this.bswPersonnes = bswPersonnes;
	}

	public Set<BswPersonne> getBswPersonnes_1() {
		return this.bswPersonnes_1;
	}

	public void setBswPersonnes_1(Set<BswPersonne> bswPersonnes_1) {
		this.bswPersonnes_1 = bswPersonnes_1;
	}

	public Set<BswgaJournalHasAbonne> getBswgaJournalHasAbonnes() {
		return this.bswgaJournalHasAbonnes;
	}

	public void setBswgaJournalHasAbonnes(
			Set<BswgaJournalHasAbonne> bswgaJournalHasAbonnes) {
		this.bswgaJournalHasAbonnes = bswgaJournalHasAbonnes;
	}

}
