package com.gj.model;

// Generated 4 mars 2014 09:23:20 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;


/**
 * BswgaTypeModeExpedition generated by hbm2java
 */
public class BswgaTypeModeExpedition   {

	private Integer idTypeModeExpedition;
	private String libelle;
	private Set<BswgaModeExpedition> bswgaModeExpeditions = new HashSet<BswgaModeExpedition>(
			0);

	public BswgaTypeModeExpedition() {
	}

	public BswgaTypeModeExpedition(String libelle,
			Set<BswgaModeExpedition> bswgaModeExpeditions) {
		this.libelle = libelle;
		this.bswgaModeExpeditions = bswgaModeExpeditions;
	}

	public Integer getIdTypeModeExpedition() {
		return this.idTypeModeExpedition;
	}

	public void setIdTypeModeExpedition(Integer idTypeModeExpedition) {
		this.idTypeModeExpedition = idTypeModeExpedition;
	}

	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	public Set<BswgaModeExpedition> getBswgaModeExpeditions() {
		return this.bswgaModeExpeditions;
	}

	public void setBswgaModeExpeditions(
			Set<BswgaModeExpedition> bswgaModeExpeditions) {
		this.bswgaModeExpeditions = bswgaModeExpeditions;
	}

}
