package com.gj.model;

// Generated 4 mars 2014 09:23:20 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * BswgaModeExpedition generated by hbm2java
 */
public class BswgaModeExpedition   {

	private Integer idModeExpedition;
	private BswJournal bswJournal;
	private BswgaTypeModeExpedition bswgaTypeModeExpedition;
	private BswgaCoordonnee bswgaCoordonnee;
	private String mode;
	private boolean defaut;
	private Set<BswgaAbonnement> bswgaAbonnements = new HashSet<BswgaAbonnement>(
			0);

	public BswgaModeExpedition() {
	}

	public BswgaModeExpedition(BswJournal bswJournal,
			BswgaTypeModeExpedition bswgaTypeModeExpedition, String mode,
			boolean defaut) {
		this.bswJournal = bswJournal;
		this.bswgaTypeModeExpedition = bswgaTypeModeExpedition;
		this.mode = mode;
		this.defaut = defaut;
	}

	public BswgaModeExpedition(BswJournal bswJournal,
			BswgaTypeModeExpedition bswgaTypeModeExpedition,
			BswgaCoordonnee bswgaCoordonnee, String mode, boolean defaut,
			Set<BswgaAbonnement> bswgaAbonnements) {
		this.bswJournal = bswJournal;
		this.bswgaTypeModeExpedition = bswgaTypeModeExpedition;
		this.bswgaCoordonnee = bswgaCoordonnee;
		this.mode = mode;
		this.defaut = defaut;
		this.bswgaAbonnements = bswgaAbonnements;
	}

	public Integer getIdModeExpedition() {
		return this.idModeExpedition;
	}

	public void setIdModeExpedition(Integer idModeExpedition) {
		this.idModeExpedition = idModeExpedition;
	}

	public BswJournal getBswJournal() {
		return this.bswJournal;
	}

	public void setBswJournal(BswJournal bswJournal) {
		this.bswJournal = bswJournal;
	}

	public BswgaTypeModeExpedition getBswgaTypeModeExpedition() {
		return this.bswgaTypeModeExpedition;
	}

	public void setBswgaTypeModeExpedition(
			BswgaTypeModeExpedition bswgaTypeModeExpedition) {
		this.bswgaTypeModeExpedition = bswgaTypeModeExpedition;
	}

	public BswgaCoordonnee getBswgaCoordonnee() {
		return this.bswgaCoordonnee;
	}

	public void setBswgaCoordonnee(BswgaCoordonnee bswgaCoordonnee) {
		this.bswgaCoordonnee = bswgaCoordonnee;
	}

	public String getMode() {
		return this.mode;
	}

	public void setMode(String mode) {
		this.mode = mode;
	}

	public boolean isDefaut() {
		return this.defaut;
	}

	public void setDefaut(boolean defaut) {
		this.defaut = defaut;
	}

	public Set<BswgaAbonnement> getBswgaAbonnements() {
		return this.bswgaAbonnements;
	}

	public void setBswgaAbonnements(Set<BswgaAbonnement> bswgaAbonnements) {
		this.bswgaAbonnements = bswgaAbonnements;
	}

}
