package com.gj.model;

// Generated 4 mars 2014 09:23:20 by Hibernate Tools 3.4.0.CR1


/**
 * BswgaJournalHasAbonne generated by hbm2java
 */
public class BswgaJournalHasAbonne  {

	private Integer idJournalHasAbonne;
	private BswJournal bswJournal;
	private BswgaTypeAbonne bswgaTypeAbonne;
	private BswgaSecteur bswgaSecteur;
	private BswgaAbonne bswgaAbonne;
	private String commentaire;
	private String referenceAbonne;

	public BswgaJournalHasAbonne() {
	}

	public BswgaJournalHasAbonne(BswJournal bswJournal,
			BswgaTypeAbonne bswgaTypeAbonne, BswgaSecteur bswgaSecteur,
			BswgaAbonne bswgaAbonne, String commentaire, String referenceAbonne) {
		this.bswJournal = bswJournal;
		this.bswgaTypeAbonne = bswgaTypeAbonne;
		this.bswgaSecteur = bswgaSecteur;
		this.bswgaAbonne = bswgaAbonne;
		this.commentaire = commentaire;
		this.referenceAbonne = referenceAbonne;
	}

	public Integer getIdJournalHasAbonne() {
		return this.idJournalHasAbonne;
	}

	public void setIdJournalHasAbonne(Integer idJournalHasAbonne) {
		this.idJournalHasAbonne = idJournalHasAbonne;
	}

	public BswJournal getBswJournal() {
		return this.bswJournal;
	}

	public void setBswJournal(BswJournal bswJournal) {
		this.bswJournal = bswJournal;
	}

	public BswgaTypeAbonne getBswgaTypeAbonne() {
		return this.bswgaTypeAbonne;
	}

	public void setBswgaTypeAbonne(BswgaTypeAbonne bswgaTypeAbonne) {
		this.bswgaTypeAbonne = bswgaTypeAbonne;
	}

	public BswgaSecteur getBswgaSecteur() {
		return this.bswgaSecteur;
	}

	public void setBswgaSecteur(BswgaSecteur bswgaSecteur) {
		this.bswgaSecteur = bswgaSecteur;
	}

	public BswgaAbonne getBswgaAbonne() {
		return this.bswgaAbonne;
	}

	public void setBswgaAbonne(BswgaAbonne bswgaAbonne) {
		this.bswgaAbonne = bswgaAbonne;
	}

	public String getCommentaire() {
		return this.commentaire;
	}

	public void setCommentaire(String commentaire) {
		this.commentaire = commentaire;
	}

	public String getReferenceAbonne() {
		return this.referenceAbonne;
	}

	public void setReferenceAbonne(String referenceAbonne) {
		this.referenceAbonne = referenceAbonne;
	}

}
