package com.gj.model;

// Generated 4 mars 2014 09:23:20 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import org.codehaus.jackson.annotate.JsonIgnore;
import org.codehaus.jackson.annotate.JsonIgnoreProperties;
import org.codehaus.jackson.annotate.JsonProperty;
import org.codehaus.jackson.map.annotate.JsonView;



/**
 * BswgaTarif generated by hbm2java
 */
@JsonIgnoreProperties(ignoreUnknown = true) 
public class BswgaTarif   {

	@JsonProperty
	private Integer idTarif;
	@JsonIgnore
	private BswJournal bswJournal;
	@JsonIgnore
	private BswgaTva bswgaTva;
	@JsonProperty
	private String nom;
	@JsonProperty
	private Integer nbNumeros;
	@JsonProperty
	private BigDecimal prixUnitaireHt;
	@JsonProperty
	private BigDecimal prixUnitaireTtc;
	@JsonProperty
	private String periode;
	@JsonProperty
	private boolean isPublic;
	@JsonIgnore
	private Set<BswgaAbonnement> bswgaAbonnements = new HashSet<BswgaAbonnement>(0);
	@JsonIgnore
	private Set<BswParution> bswParutions = new HashSet<BswParution>(0);

	public BswgaTarif() {
	}

	public BswgaTarif(BswgaTva bswgaTva, boolean isPublic) {
		this.bswgaTva = bswgaTva;
		this.isPublic = isPublic;
	}

	public BswgaTarif(BswJournal bswJournal, BswgaTva bswgaTva, String nom,
			Integer nbNumeros, BigDecimal prixUnitaireHt,
			BigDecimal prixUnitaireTtc, String periode, boolean isPublic,
			Set<BswgaAbonnement> bswgaAbonnements, Set<BswParution> bswParutions) {
		this.bswJournal = bswJournal;
		this.bswgaTva = bswgaTva;
		this.nom = nom;
		this.nbNumeros = nbNumeros;
		this.prixUnitaireHt = prixUnitaireHt;
		this.prixUnitaireTtc = prixUnitaireTtc;
		this.periode = periode;
		this.isPublic = isPublic;
		this.bswgaAbonnements = bswgaAbonnements;
		this.bswParutions = bswParutions;
	}

	public Integer getIdTarif() {
		return this.idTarif;
	}

	public void setIdTarif(Integer idTarif) {
		this.idTarif = idTarif;
	}

	public BswJournal getBswJournal() {
		return this.bswJournal;
	}

	public void setBswJournal(BswJournal bswJournal) {
		this.bswJournal = bswJournal;
	}

	public BswgaTva getBswgaTva() {
		return this.bswgaTva;
	}

	public void setBswgaTva(BswgaTva bswgaTva) {
		this.bswgaTva = bswgaTva;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public Integer getNbNumeros() {
		return this.nbNumeros;
	}

	public void setNbNumeros(Integer nbNumeros) {
		this.nbNumeros = nbNumeros;
	}

	public BigDecimal getPrixUnitaireHt() {
		return this.prixUnitaireHt;
	}

	public void setPrixUnitaireHt(BigDecimal prixUnitaireHt) {
		this.prixUnitaireHt = prixUnitaireHt;
	}

	public BigDecimal getPrixUnitaireTtc() {
		return this.prixUnitaireTtc;
	}

	public void setPrixUnitaireTtc(BigDecimal prixUnitaireTtc) {
		this.prixUnitaireTtc = prixUnitaireTtc;
	}

	public String getPeriode() {
		return this.periode;
	}

	public void setPeriode(String periode) {
		this.periode = periode;
	}

	public boolean isIsPublic() {
		return this.isPublic;
	}

	public void setIsPublic(boolean isPublic) {
		this.isPublic = isPublic;
	}

	public Set<BswgaAbonnement> getBswgaAbonnements() {
		return this.bswgaAbonnements;
	}

	public void setBswgaAbonnements(Set<BswgaAbonnement> bswgaAbonnements) {
		this.bswgaAbonnements = bswgaAbonnements;
	}

	public Set<BswParution> getBswParutions() {
		return this.bswParutions;
	}

	public void setBswParutions(Set<BswParution> bswParutions) {
		this.bswParutions = bswParutions;
	}

}
