package com.gj.model;

// Generated 4 mars 2014 09:23:20 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;


/**
 * BswgaPaiement generated by hbm2java
 */
public class BswgaPaiement   {

	private Integer idPaiement;
	private BswgaAbonnement bswgaAbonnement;
	private Date date;
	private String modePaiement;
	private String libelle;
	private BigDecimal montant;
	private String nomPayeur;
	private String banque;
	private Date dateDepot;
	private Date dateEncaissement;
	private String banqueStatut;
	private String banqueReference;
	private String banqueLogs;
	private String commentaire;

	public BswgaPaiement() {
	}

	public BswgaPaiement(BswgaAbonnement bswgaAbonnement, Date date,
			String modePaiement, String libelle, BigDecimal montant,
			String nomPayeur, String banque, Date dateDepot,
			Date dateEncaissement, String banqueStatut, String banqueReference,
			String banqueLogs, String commentaire) {
		this.bswgaAbonnement = bswgaAbonnement;
		this.date = date;
		this.modePaiement = modePaiement;
		this.libelle = libelle;
		this.montant = montant;
		this.nomPayeur = nomPayeur;
		this.banque = banque;
		this.dateDepot = dateDepot;
		this.dateEncaissement = dateEncaissement;
		this.banqueStatut = banqueStatut;
		this.banqueReference = banqueReference;
		this.banqueLogs = banqueLogs;
		this.commentaire = commentaire;
	}

	public Integer getIdPaiement() {
		return this.idPaiement;
	}

	public void setIdPaiement(Integer idPaiement) {
		this.idPaiement = idPaiement;
	}

	public BswgaAbonnement getBswgaAbonnement() {
		return this.bswgaAbonnement;
	}

	public void setBswgaAbonnement(BswgaAbonnement bswgaAbonnement) {
		this.bswgaAbonnement = bswgaAbonnement;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public String getModePaiement() {
		return this.modePaiement;
	}

	public void setModePaiement(String modePaiement) {
		this.modePaiement = modePaiement;
	}

	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	public BigDecimal getMontant() {
		return this.montant;
	}

	public void setMontant(BigDecimal montant) {
		this.montant = montant;
	}

	public String getNomPayeur() {
		return this.nomPayeur;
	}

	public void setNomPayeur(String nomPayeur) {
		this.nomPayeur = nomPayeur;
	}

	public String getBanque() {
		return this.banque;
	}

	public void setBanque(String banque) {
		this.banque = banque;
	}

	public Date getDateDepot() {
		return this.dateDepot;
	}

	public void setDateDepot(Date dateDepot) {
		this.dateDepot = dateDepot;
	}

	public Date getDateEncaissement() {
		return this.dateEncaissement;
	}

	public void setDateEncaissement(Date dateEncaissement) {
		this.dateEncaissement = dateEncaissement;
	}

	public String getBanqueStatut() {
		return this.banqueStatut;
	}

	public void setBanqueStatut(String banqueStatut) {
		this.banqueStatut = banqueStatut;
	}

	public String getBanqueReference() {
		return this.banqueReference;
	}

	public void setBanqueReference(String banqueReference) {
		this.banqueReference = banqueReference;
	}

	public String getBanqueLogs() {
		return this.banqueLogs;
	}

	public void setBanqueLogs(String banqueLogs) {
		this.banqueLogs = banqueLogs;
	}

	public String getCommentaire() {
		return this.commentaire;
	}

	public void setCommentaire(String commentaire) {
		this.commentaire = commentaire;
	}

}
