package com.gj.model;

// Generated 4 mars 2014 09:23:20 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;



/**
 * BswgaAbonnement generated by hbm2java
 */
public class BswgaAbonnement   {

	private Integer idAbonnement;
	private BswgaModeExpedition bswgaModeExpedition;
	private BswgaTarif bswgaTarif;
	private BswJournal bswJournal;
	private BswgaAbonne bswgaAbonne;
	private BswgaCoordonnee bswgaCoordonnee;
	private Integer nbExemplaires;
	private Integer numeroDebut;
	private Integer numeroFin;
	private Date date;
	private boolean reabonnement;
	private boolean renouvellementAuto;
	private BigDecimal prixUnitaireTtc;
	private BigDecimal tauxTva;
	private Set<BswgaPaiement> bswgaPaiements = new HashSet<BswgaPaiement>(0);
	private Set<BswgaFacture> bswgaFactures = new HashSet<BswgaFacture>(0);

	public BswgaAbonnement() {
	}

	public BswgaAbonnement(boolean reabonnement, boolean renouvellementAuto,
			BigDecimal prixUnitaireTtc, BigDecimal tauxTva) {
		this.reabonnement = reabonnement;
		this.renouvellementAuto = renouvellementAuto;
		this.prixUnitaireTtc = prixUnitaireTtc;
		this.tauxTva = tauxTva;
	}

	public BswgaAbonnement(BswgaModeExpedition bswgaModeExpedition,
			BswgaTarif bswgaTarif, BswJournal bswJournal,
			BswgaAbonne bswgaAbonne, BswgaCoordonnee bswgaCoordonnee,
			Integer nbExemplaires, Integer numeroDebut, Integer numeroFin,
			Date date, boolean reabonnement, boolean renouvellementAuto,
			BigDecimal prixUnitaireTtc, BigDecimal tauxTva,
			Set<BswgaPaiement> bswgaPaiements, Set<BswgaFacture> bswgaFactures) {
		this.bswgaModeExpedition = bswgaModeExpedition;
		this.bswgaTarif = bswgaTarif;
		this.bswJournal = bswJournal;
		this.bswgaAbonne = bswgaAbonne;
		this.bswgaCoordonnee = bswgaCoordonnee;
		this.nbExemplaires = nbExemplaires;
		this.numeroDebut = numeroDebut;
		this.numeroFin = numeroFin;
		this.date = date;
		this.reabonnement = reabonnement;
		this.renouvellementAuto = renouvellementAuto;
		this.prixUnitaireTtc = prixUnitaireTtc;
		this.tauxTva = tauxTva;
		this.bswgaPaiements = bswgaPaiements;
		this.bswgaFactures = bswgaFactures;
	}

	public Integer getIdAbonnement() {
		return this.idAbonnement;
	}

	public void setIdAbonnement(Integer idAbonnement) {
		this.idAbonnement = idAbonnement;
	}

	public BswgaModeExpedition getBswgaModeExpedition() {
		return this.bswgaModeExpedition;
	}

	public void setBswgaModeExpedition(BswgaModeExpedition bswgaModeExpedition) {
		this.bswgaModeExpedition = bswgaModeExpedition;
	}

	public BswgaTarif getBswgaTarif() {
		return this.bswgaTarif;
	}

	public void setBswgaTarif(BswgaTarif bswgaTarif) {
		this.bswgaTarif = bswgaTarif;
	}

	public BswJournal getBswJournal() {
		return this.bswJournal;
	}

	public void setBswJournal(BswJournal bswJournal) {
		this.bswJournal = bswJournal;
	}

	public BswgaAbonne getBswgaAbonne() {
		return this.bswgaAbonne;
	}

	public void setBswgaAbonne(BswgaAbonne bswgaAbonne) {
		this.bswgaAbonne = bswgaAbonne;
	}

	public BswgaCoordonnee getBswgaCoordonnee() {
		return this.bswgaCoordonnee;
	}

	public void setBswgaCoordonnee(BswgaCoordonnee bswgaCoordonnee) {
		this.bswgaCoordonnee = bswgaCoordonnee;
	}

	public Integer getNbExemplaires() {
		return this.nbExemplaires;
	}

	public void setNbExemplaires(Integer nbExemplaires) {
		this.nbExemplaires = nbExemplaires;
	}

	public Integer getNumeroDebut() {
		return this.numeroDebut;
	}

	public void setNumeroDebut(Integer numeroDebut) {
		this.numeroDebut = numeroDebut;
	}

	public Integer getNumeroFin() {
		return this.numeroFin;
	}

	public void setNumeroFin(Integer numeroFin) {
		this.numeroFin = numeroFin;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public boolean isReabonnement() {
		return this.reabonnement;
	}

	public void setReabonnement(boolean reabonnement) {
		this.reabonnement = reabonnement;
	}

	public boolean isRenouvellementAuto() {
		return this.renouvellementAuto;
	}

	public void setRenouvellementAuto(boolean renouvellementAuto) {
		this.renouvellementAuto = renouvellementAuto;
	}

	public BigDecimal getPrixUnitaireTtc() {
		return this.prixUnitaireTtc;
	}

	public void setPrixUnitaireTtc(BigDecimal prixUnitaireTtc) {
		this.prixUnitaireTtc = prixUnitaireTtc;
	}

	public BigDecimal getTauxTva() {
		return this.tauxTva;
	}

	public void setTauxTva(BigDecimal tauxTva) {
		this.tauxTva = tauxTva;
	}

	public Set<BswgaPaiement> getBswgaPaiements() {
		return this.bswgaPaiements;
	}

	public void setBswgaPaiements(Set<BswgaPaiement> bswgaPaiements) {
		this.bswgaPaiements = bswgaPaiements;
	}

	public Set<BswgaFacture> getBswgaFactures() {
		return this.bswgaFactures;
	}

	public void setBswgaFactures(Set<BswgaFacture> bswgaFactures) {
		this.bswgaFactures = bswgaFactures;
	}

}
