package com.gj.model;

// Generated 4 mars 2014 09:23:20 by Hibernate Tools 3.4.0.CR1


/**
 * BswgaModele generated by hbm2java
 */
public class BswgaModele   {

	private Integer idModele;
	private BswJournal bswJournal;
	private String nom;
	private String expediteur;
	private String adresse;
	private String email;
	private String objet;
	private String contenu;
	private String signature;
	private String type;

	public BswgaModele() {
	}

	public BswgaModele(BswJournal bswJournal) {
		this.bswJournal = bswJournal;
	}

	public BswgaModele(BswJournal bswJournal, String nom, String expediteur,
			String adresse, String email, String objet, String contenu,
			String signature, String type) {
		this.bswJournal = bswJournal;
		this.nom = nom;
		this.expediteur = expediteur;
		this.adresse = adresse;
		this.email = email;
		this.objet = objet;
		this.contenu = contenu;
		this.signature = signature;
		this.type = type;
	}

	public Integer getIdModele() {
		return this.idModele;
	}

	public void setIdModele(Integer idModele) {
		this.idModele = idModele;
	}

	public BswJournal getBswJournal() {
		return this.bswJournal;
	}

	public void setBswJournal(BswJournal bswJournal) {
		this.bswJournal = bswJournal;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getExpediteur() {
		return this.expediteur;
	}

	public void setExpediteur(String expediteur) {
		this.expediteur = expediteur;
	}

	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getObjet() {
		return this.objet;
	}

	public void setObjet(String objet) {
		this.objet = objet;
	}

	public String getContenu() {
		return this.contenu;
	}

	public void setContenu(String contenu) {
		this.contenu = contenu;
	}

	public String getSignature() {
		return this.signature;
	}

	public void setSignature(String signature) {
		this.signature = signature;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
