package com.gj.model;

// Generated 4 mars 2014 09:23:20 by Hibernate Tools 3.4.0.CR1

import java.util.Date;


/**
 * BswgaEtatJasper generated by hbm2java
 */
public class BswgaEtatJasper{

	private Integer idEtatJasper;
	private String titre;
	private String cible;
	private String xml;
	private Date dateModif;

	public BswgaEtatJasper() {
	}

	public BswgaEtatJasper(String titre, String cible, String xml,
			Date dateModif) {
		this.titre = titre;
		this.cible = cible;
		this.xml = xml;
		this.dateModif = dateModif;
	}

	public Integer getIdEtatJasper() {
		return this.idEtatJasper;
	}

	public void setIdEtatJasper(Integer idEtatJasper) {
		this.idEtatJasper = idEtatJasper;
	}

	public String getTitre() {
		return this.titre;
	}

	public void setTitre(String titre) {
		this.titre = titre;
	}

	public String getCible() {
		return this.cible;
	}

	public void setCible(String cible) {
		this.cible = cible;
	}

	public String getXml() {
		return this.xml;
	}

	public void setXml(String xml) {
		this.xml = xml;
	}

	public Date getDateModif() {
		return this.dateModif;
	}

	public void setDateModif(Date dateModif) {
		this.dateModif = dateModif;
	}

}
