package com.gj.model;

// Generated 4 mars 2014 09:23:20 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import org.codehaus.jackson.map.annotate.JsonView;




/**
 * BswgaCoordonnee generated by hbm2java
 */
public class BswgaCoordonnee {

	@JsonView
	private Integer idCoordonnee;
	@JsonView
	private BswgaPays bswgaPays;
	@JsonView
	private String libelle;
	@JsonView
	private String tel;
	@JsonView
	private String fax;
	@JsonView
	private String mobile;
	@JsonView
	private String email;
	@JsonView
	private String siteWeb;
	@JsonView
	private String typeAdressePostale;
	@JsonView
	private String destinataire;
	@JsonView
	private String destinataireComplement;
	@JsonView
	private String adresseLigne1;
	@JsonView
	private String numeroVoie;
	@JsonView
	private String libelleVoie;
	@JsonView
	private String adresseLigne3;
	@JsonView
	private String codePostal;
	@JsonView
	private String ville;
	@JsonView
	private String cedex;
	@JsonView
	private boolean defaut;
	private Set<BswgaModeExpedition> bswgaModeExpeditions = new HashSet<BswgaModeExpedition>(
			0);
	private Set<BswgaAbonnement> bswgaAbonnements = new HashSet<BswgaAbonnement>(
			0);
	private Set<BswgaAbonne> bswgaAbonnes = new HashSet<BswgaAbonne>(0);

	public BswgaCoordonnee() {
	}

	public BswgaCoordonnee(BswgaPays bswgaPays, boolean defaut) {
		this.bswgaPays = bswgaPays;
		this.defaut = defaut;
	}

	public BswgaCoordonnee(BswgaPays bswgaPays, String libelle, String tel,
			String fax, String mobile, String email, String siteWeb,
			String typeAdressePostale, String destinataire,
			String destinataireComplement, String adresseLigne1,
			String numeroVoie, String libelleVoie, String adresseLigne3,
			String codePostal, String ville, String cedex, boolean defaut,
			Set<BswgaModeExpedition> bswgaModeExpeditions,
			Set<BswgaAbonnement> bswgaAbonnements, Set<BswgaAbonne> bswgaAbonnes) {
		this.bswgaPays = bswgaPays;
		this.libelle = libelle;
		this.tel = tel;
		this.fax = fax;
		this.mobile = mobile;
		this.email = email;
		this.siteWeb = siteWeb;
		this.typeAdressePostale = typeAdressePostale;
		this.destinataire = destinataire;
		this.destinataireComplement = destinataireComplement;
		this.adresseLigne1 = adresseLigne1;
		this.numeroVoie = numeroVoie;
		this.libelleVoie = libelleVoie;
		this.adresseLigne3 = adresseLigne3;
		this.codePostal = codePostal;
		this.ville = ville;
		this.cedex = cedex;
		this.defaut = defaut;
		this.bswgaModeExpeditions = bswgaModeExpeditions;
		this.bswgaAbonnements = bswgaAbonnements;
		this.bswgaAbonnes = bswgaAbonnes;
	}

	public Integer getIdCoordonnee() {
		return this.idCoordonnee;
	}

	public void setIdCoordonnee(Integer idCoordonnee) {
		this.idCoordonnee = idCoordonnee;
	}

	public BswgaPays getBswgaPays() {
		return this.bswgaPays;
	}

	public void setBswgaPays(BswgaPays bswgaPays) {
		this.bswgaPays = bswgaPays;
	}

	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getSiteWeb() {
		return this.siteWeb;
	}

	public void setSiteWeb(String siteWeb) {
		this.siteWeb = siteWeb;
	}

	public String getTypeAdressePostale() {
		return this.typeAdressePostale;
	}

	public void setTypeAdressePostale(String typeAdressePostale) {
		this.typeAdressePostale = typeAdressePostale;
	}

	public String getDestinataire() {
		return this.destinataire;
	}

	public void setDestinataire(String destinataire) {
		this.destinataire = destinataire;
	}

	public String getDestinataireComplement() {
		return this.destinataireComplement;
	}

	public void setDestinataireComplement(String destinataireComplement) {
		this.destinataireComplement = destinataireComplement;
	}

	public String getAdresseLigne1() {
		return this.adresseLigne1;
	}

	public void setAdresseLigne1(String adresseLigne1) {
		this.adresseLigne1 = adresseLigne1;
	}

	public String getNumeroVoie() {
		return this.numeroVoie;
	}

	public void setNumeroVoie(String numeroVoie) {
		this.numeroVoie = numeroVoie;
	}

	public String getLibelleVoie() {
		return this.libelleVoie;
	}

	public void setLibelleVoie(String libelleVoie) {
		this.libelleVoie = libelleVoie;
	}

	public String getAdresseLigne3() {
		return this.adresseLigne3;
	}

	public void setAdresseLigne3(String adresseLigne3) {
		this.adresseLigne3 = adresseLigne3;
	}

	public String getCodePostal() {
		return this.codePostal;
	}

	public void setCodePostal(String codePostal) {
		this.codePostal = codePostal;
	}

	public String getVille() {
		return this.ville;
	}

	public void setVille(String ville) {
		this.ville = ville;
	}

	public String getCedex() {
		return this.cedex;
	}

	public void setCedex(String cedex) {
		this.cedex = cedex;
	}

	public boolean isDefaut() {
		return this.defaut;
	}

	public void setDefaut(boolean defaut) {
		this.defaut = defaut;
	}

	public Set<BswgaModeExpedition> getBswgaModeExpeditions() {
		return this.bswgaModeExpeditions;
	}

	public void setBswgaModeExpeditions(
			Set<BswgaModeExpedition> bswgaModeExpeditions) {
		this.bswgaModeExpeditions = bswgaModeExpeditions;
	}

	public Set<BswgaAbonnement> getBswgaAbonnements() {
		return this.bswgaAbonnements;
	}

	public void setBswgaAbonnements(Set<BswgaAbonnement> bswgaAbonnements) {
		this.bswgaAbonnements = bswgaAbonnements;
	}

	public Set<BswgaAbonne> getBswgaAbonnes() {
		return this.bswgaAbonnes;
	}

	public void setBswgaAbonnes(Set<BswgaAbonne> bswgaAbonnes) {
		this.bswgaAbonnes = bswgaAbonnes;
	}

}
