package com.gj.model;

// Generated 4 mars 2014 09:23:20 by Hibernate Tools 3.4.0.CR1

import java.util.Date;



/**
 * BswgaFacture generated by hbm2java
 */
public class BswgaFacture   {

	private Integer idFacture;
	private BswgaAbonnement bswgaAbonnement;
	private String referenceFacture;
	private Date date;
	private String observations;
	private String statut;

	public BswgaFacture() {
	}

	public BswgaFacture(BswgaAbonnement bswgaAbonnement,
			String referenceFacture, Date date, String observations,
			String statut) {
		this.bswgaAbonnement = bswgaAbonnement;
		this.referenceFacture = referenceFacture;
		this.date = date;
		this.observations = observations;
		this.statut = statut;
	}

	public Integer getIdFacture() {
		return this.idFacture;
	}

	public void setIdFacture(Integer idFacture) {
		this.idFacture = idFacture;
	}

	public BswgaAbonnement getBswgaAbonnement() {
		return this.bswgaAbonnement;
	}

	public void setBswgaAbonnement(BswgaAbonnement bswgaAbonnement) {
		this.bswgaAbonnement = bswgaAbonnement;
	}

	public String getReferenceFacture() {
		return this.referenceFacture;
	}

	public void setReferenceFacture(String referenceFacture) {
		this.referenceFacture = referenceFacture;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public String getObservations() {
		return this.observations;
	}

	public void setObservations(String observations) {
		this.observations = observations;
	}

	public String getStatut() {
		return this.statut;
	}

	public void setStatut(String statut) {
		this.statut = statut;
	}

}
