package com.gj.model;


// Generated 4 mars 2014 09:23:20 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import org.codehaus.jackson.annotate.JsonIgnore;
import org.codehaus.jackson.map.annotate.JsonView;


/**
 * BswgaTva generated by hbm2java
 */
public class BswgaTva   {

	@JsonView
	private Integer idTva;
	@JsonView
	private BigDecimal taux;
	@JsonIgnore
	private Set<BswgaTarif> bswgaTarifs = new HashSet<BswgaTarif>(0);

	public BswgaTva() {
	}

	public BswgaTva(BigDecimal taux, Set<BswgaTarif> bswgaTarifs) {
		this.taux = taux;
		this.bswgaTarifs = bswgaTarifs;
	}

	public Integer getIdTva() {
		return this.idTva;
	}

	public void setIdTva(Integer idTva) {
		this.idTva = idTva;
	}

	public BigDecimal getTaux() {
		return this.taux;
	}

	public void setTaux(BigDecimal taux) {
		this.taux = taux;
	}

	public Set<BswgaTarif> getBswgaTarifs() {
		return this.bswgaTarifs;
	}

	public void setBswgaTarifs(Set<BswgaTarif> bswgaTarifs) {
		this.bswgaTarifs = bswgaTarifs;
	}

}
