package com.gj.model;
// Generated 4 mars 2014 09:23:20 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;



/**
 * BswgaAbonne generated by hbm2java
 */
public class BswgaAbonne   {

	private Integer idAbonne;
	private BswgaCivilite bswgaCivilite;
	private BswgaCoordonnee bswgaCoordonnee;
	private String nom;
	private String prenom;
	private String particule;
	private String genre;
	private Date dateNaissance;
	private String societe;
	private String login;
	private String mdp;
	private Date dateCreation;
	private Date dateModification;
	private String auteurCreation;
	private String auteurModification;
	private Set<BswgaJournalHasAbonne> bswgaJournalHasAbonnes = new HashSet<BswgaJournalHasAbonne>(
			0);
	private Set<BswgaAbonnement> bswgaAbonnements = new HashSet<BswgaAbonnement>(
			0);

	public BswgaAbonne() {
	}

	public BswgaAbonne(BswgaCivilite bswgaCivilite,
			BswgaCoordonnee bswgaCoordonnee, String nom, String prenom,
			String particule, String genre, Date dateNaissance, String societe,
			String login, String mdp, Date dateCreation, Date dateModification,
			String auteurCreation, String auteurModification,
			Set<BswgaJournalHasAbonne> bswgaJournalHasAbonnes,
			Set<BswgaAbonnement> bswgaAbonnements) {
		this.bswgaCivilite = bswgaCivilite;
		this.bswgaCoordonnee = bswgaCoordonnee;
		this.nom = nom;
		this.prenom = prenom;
		this.particule = particule;
		this.genre = genre;
		this.dateNaissance = dateNaissance;
		this.societe = societe;
		this.login = login;
		this.mdp = mdp;
		this.dateCreation = dateCreation;
		this.dateModification = dateModification;
		this.auteurCreation = auteurCreation;
		this.auteurModification = auteurModification;
		this.bswgaJournalHasAbonnes = bswgaJournalHasAbonnes;
		this.bswgaAbonnements = bswgaAbonnements;
	}

	public Integer getIdAbonne() {
		return this.idAbonne;
	}

	public void setIdAbonne(Integer idAbonne) {
		this.idAbonne = idAbonne;
	}

	public BswgaCivilite getBswgaCivilite() {
		return this.bswgaCivilite;
	}

	public void setBswgaCivilite(BswgaCivilite bswgaCivilite) {
		this.bswgaCivilite = bswgaCivilite;
	}

	public BswgaCoordonnee getBswgaCoordonnee() {
		return this.bswgaCoordonnee;
	}

	public void setBswgaCoordonnee(BswgaCoordonnee bswgaCoordonnee) {
		this.bswgaCoordonnee = bswgaCoordonnee;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	public String getParticule() {
		return this.particule;
	}

	public void setParticule(String particule) {
		this.particule = particule;
	}

	public String getGenre() {
		return this.genre;
	}

	public void setGenre(String genre) {
		this.genre = genre;
	}

	public Date getDateNaissance() {
		return this.dateNaissance;
	}

	public void setDateNaissance(Date dateNaissance) {
		this.dateNaissance = dateNaissance;
	}

	public String getSociete() {
		return this.societe;
	}

	public void setSociete(String societe) {
		this.societe = societe;
	}

	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getMdp() {
		return this.mdp;
	}

	public void setMdp(String mdp) {
		this.mdp = mdp;
	}

	public Date getDateCreation() {
		return this.dateCreation;
	}

	public void setDateCreation(Date dateCreation) {
		this.dateCreation = dateCreation;
	}

	public Date getDateModification() {
		return this.dateModification;
	}

	public void setDateModification(Date dateModification) {
		this.dateModification = dateModification;
	}

	public String getAuteurCreation() {
		return this.auteurCreation;
	}

	public void setAuteurCreation(String auteurCreation) {
		this.auteurCreation = auteurCreation;
	}

	public String getAuteurModification() {
		return this.auteurModification;
	}

	public void setAuteurModification(String auteurModification) {
		this.auteurModification = auteurModification;
	}

	public Set<BswgaJournalHasAbonne> getBswgaJournalHasAbonnes() {
		return this.bswgaJournalHasAbonnes;
	}

	public void setBswgaJournalHasAbonnes(
			Set<BswgaJournalHasAbonne> bswgaJournalHasAbonnes) {
		this.bswgaJournalHasAbonnes = bswgaJournalHasAbonnes;
	}

	public Set<BswgaAbonnement> getBswgaAbonnements() {
		return this.bswgaAbonnements;
	}

	public void setBswgaAbonnements(Set<BswgaAbonnement> bswgaAbonnements) {
		this.bswgaAbonnements = bswgaAbonnements;
	}

}
