package com.gj.model;

// Generated 4 mars 2014 09:23:20 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import org.codehaus.jackson.annotate.JsonIgnore;
import org.codehaus.jackson.map.annotate.JsonView;

import java.io.Serializable;

/**
 * BswJournal generated by hbm2java
 */
public class BswJournal implements Serializable {

	@JsonView
	private Integer idJournal;
	@JsonView
	private BswUnitorg bswUnitorgByIdUnitorgBayard;
	@JsonView
	private BswUnitorg bswUnitorgByIdUnitorgClient;
	@JsonIgnore
	private BswPersonne bswPersonneByIdResponsableAbonne;
	@JsonIgnore
	private BswPersonne bswPersonneByIdResponsable;
	@JsonIgnore
	private BswSousFamille bswSousFamille;
	@JsonView
	private BswUnitorg bswUnitorgByIdUnitorgImprimeur;
	@JsonIgnore
	private BswPersonne bswPersonneByIdReferent;
	@JsonIgnore
	private BswFamille bswFamille;
	@JsonView
	private String titre;
	@JsonView
	private String sousTitre;
	@JsonView
	private String code;
	@JsonView
	private String lieu;
	@JsonView
	private Integer nbParutions;
	@JsonView
	private Integer nbPages;
	@JsonView
	private Boolean fondCommun;
	@JsonView
	private String commentaire;
	@JsonView
	private Boolean abonnementOuvert;
	@JsonView
	private boolean paiementCb;
	@JsonView
	private String formatFacture;
	@JsonView
	private String formatClient;
	@JsonView
	private Date dateCreation;
	@JsonView
	private Date dateModification;
	@JsonView
	private String auteurCreation;
	@JsonView
	private String auteurModification;
	@JsonView
	private String urlApercuVignette;
	@JsonView
	private String urlPagePresentation;
	@JsonView
	private String localite;
	@JsonView
	private String sequencePagination;
	@JsonView
	private String reference;
	@JsonView
	private Boolean fusionDesUrs;
	@JsonView
	private String siteGeneBase;
	@JsonView
	private String siteGeneUrl;
	@JsonView
	private String siteGeneLogin;
	@JsonView
	private String siteGeneMdp;
	@JsonView
	private boolean miseEnFormeEtendue;
	@JsonIgnore
	private Set<BswgaJournalHasAbonne> bswgaJournalHasAbonnes = new HashSet<BswgaJournalHasAbonne>(
			0);
	@JsonIgnore
	private Set<BswConfigurationPaiement> bswConfigurationPaiements = new HashSet<BswConfigurationPaiement>(
			0);
	@JsonIgnore
	private Set<BswMultiSites> bswMultiSiteses = new HashSet<BswMultiSites>(0);
	@JsonIgnore
	private Set<BswUnitorg> bswUnitorgs = new HashSet<BswUnitorg>(0);
	@JsonIgnore
	private Set<BswApplication> bswApplications = new HashSet<BswApplication>(0);
	@JsonIgnore
	private Set<BswgaTypeAbonne> bswgaTypeAbonnes = new HashSet<BswgaTypeAbonne>(
			0);
	@JsonIgnore
	private Set<BswdtPage> bswdtPages = new HashSet<BswdtPage>(0);
	@JsonIgnore
	private Set<BswPersonne> bswPersonnes = new HashSet<BswPersonne>(0);
	@JsonIgnore
	private Set<BswgaModeExpedition> bswgaModeExpeditions = new HashSet<BswgaModeExpedition>(
			0);
	@JsonIgnore
	private Set<BswParution> bswParutions = new HashSet<BswParution>(0);
	@JsonIgnore
	private Set<BswgaAbonnement> bswgaAbonnements = new HashSet<BswgaAbonnement>(
			0);
	@JsonIgnore
	private Set<BswdtModelPage> bswdtModelPages = new HashSet<BswdtModelPage>(0);
	@JsonIgnore
	private Set<BswgaSecteur> bswgaSecteurs = new HashSet<BswgaSecteur>(0);
	@JsonIgnore
	private Set<BswgaTarif> bswgaTarifs = new HashSet<BswgaTarif>(0);
	@JsonIgnore
	private Set<BswgaModele> bswgaModeles = new HashSet<BswgaModele>(0);
	@JsonIgnore
	private Set<BswJournal> bswJournalsForIdJournal = new HashSet<BswJournal>(0);
	@JsonIgnore
	private Set<BswPersonne> bswPersonnes_1 = new HashSet<BswPersonne>(0);
	@JsonIgnore
	private Set<BswJournal> bswJournalsForIdJournalFondCommun = new HashSet<BswJournal>(
			0);
	@JsonIgnore
	private Set<BswSecteur> bswSecteurs = new HashSet<BswSecteur>(0);
	@JsonIgnore
	private Set<BswDepartement> bswDepartements = new HashSet<BswDepartement>(0);

	public BswJournal() {
	}

	public BswJournal(boolean paiementCb, boolean miseEnFormeEtendue) {
		this.paiementCb = paiementCb;
		this.miseEnFormeEtendue = miseEnFormeEtendue;
	}

	public BswJournal(BswUnitorg bswUnitorgByIdUnitorgBayard,
			BswUnitorg bswUnitorgByIdUnitorgClient,
			BswPersonne bswPersonneByIdResponsableAbonne,
			BswPersonne bswPersonneByIdResponsable,
			BswSousFamille bswSousFamille,
			BswUnitorg bswUnitorgByIdUnitorgImprimeur,
			BswPersonne bswPersonneByIdReferent, BswFamille bswFamille,
			String titre, String sousTitre, String code, String lieu,
			Integer nbParutions, Integer nbPages, Boolean fondCommun,
			String commentaire, Boolean abonnementOuvert, boolean paiementCb,
			String formatFacture, String formatClient, Date dateCreation,
			Date dateModification, String auteurCreation,
			String auteurModification, String urlApercuVignette,
			String urlPagePresentation, String localite,
			String sequencePagination, String reference, Boolean fusionDesUrs,
			String siteGeneBase, String siteGeneUrl, String siteGeneLogin,
			String siteGeneMdp, boolean miseEnFormeEtendue,
			Set<BswgaJournalHasAbonne> bswgaJournalHasAbonnes,
			Set<BswConfigurationPaiement> bswConfigurationPaiements,
			Set<BswApplication> bswApplications,
			Set<BswgaTypeAbonne> bswgaTypeAbonnes, Set<BswdtPage> bswdtPages,
			Set<BswPersonne> bswPersonnes,
			Set<BswgaModeExpedition> bswgaModeExpeditions,
			Set<BswParution> bswParutions,
			Set<BswgaAbonnement> bswgaAbonnements,
			Set<BswdtModelPage> bswdtModelPages,
			Set<BswgaSecteur> bswgaSecteurs, Set<BswgaTarif> bswgaTarifs,
			Set<BswgaModele> bswgaModeles,
			Set<BswJournal> bswJournalsForIdJournal,
			Set<BswPersonne> bswPersonnes_1,
			Set<BswJournal> bswJournalsForIdJournalFondCommun,
			Set<BswSecteur> bswSecteurs, Set<BswDepartement> bswDepartements) {
		this.bswUnitorgByIdUnitorgBayard = bswUnitorgByIdUnitorgBayard;
		this.bswUnitorgByIdUnitorgClient = bswUnitorgByIdUnitorgClient;
		this.bswPersonneByIdResponsableAbonne = bswPersonneByIdResponsableAbonne;
		this.bswPersonneByIdResponsable = bswPersonneByIdResponsable;
		this.bswSousFamille = bswSousFamille;
		this.bswUnitorgByIdUnitorgImprimeur = bswUnitorgByIdUnitorgImprimeur;
		this.bswPersonneByIdReferent = bswPersonneByIdReferent;
		this.bswFamille = bswFamille;
		this.titre = titre;
		this.sousTitre = sousTitre;
		this.code = code;
		this.lieu = lieu;
		this.nbParutions = nbParutions;
		this.nbPages = nbPages;
		this.fondCommun = fondCommun;
		this.commentaire = commentaire;
		this.abonnementOuvert = abonnementOuvert;
		this.paiementCb = paiementCb;
		this.formatFacture = formatFacture;
		this.formatClient = formatClient;
		this.dateCreation = dateCreation;
		this.dateModification = dateModification;
		this.auteurCreation = auteurCreation;
		this.auteurModification = auteurModification;
		this.urlApercuVignette = urlApercuVignette;
		this.urlPagePresentation = urlPagePresentation;
		this.localite = localite;
		this.sequencePagination = sequencePagination;
		this.reference = reference;
		this.fusionDesUrs = fusionDesUrs;
		this.siteGeneBase = siteGeneBase;
		this.siteGeneUrl = siteGeneUrl;
		this.siteGeneLogin = siteGeneLogin;
		this.siteGeneMdp = siteGeneMdp;
		this.miseEnFormeEtendue = miseEnFormeEtendue;
		this.bswgaJournalHasAbonnes = bswgaJournalHasAbonnes;
		this.bswConfigurationPaiements = bswConfigurationPaiements;
		this.bswMultiSiteses = bswMultiSiteses;
		this.bswUnitorgs = bswUnitorgs;
		this.bswApplications = bswApplications;
		this.bswgaTypeAbonnes = bswgaTypeAbonnes;
		this.bswdtPages = bswdtPages;
		this.bswPersonnes = bswPersonnes;
		this.bswgaModeExpeditions = bswgaModeExpeditions;
		this.bswParutions = bswParutions;
		this.bswgaAbonnements = bswgaAbonnements;
		this.bswdtModelPages = bswdtModelPages;
		this.bswgaSecteurs = bswgaSecteurs;
		this.bswgaTarifs = bswgaTarifs;
		this.bswgaModeles = bswgaModeles;
		this.bswJournalsForIdJournal = bswJournalsForIdJournal;
		this.bswPersonnes_1 = bswPersonnes_1;
		this.bswJournalsForIdJournalFondCommun = bswJournalsForIdJournalFondCommun;
		this.bswSecteurs = bswSecteurs;
		this.bswDepartements = bswDepartements;
	}

	public Integer getIdJournal() {
		return this.idJournal;
	}

	public void setIdJournal(Integer idJournal) {
		this.idJournal = idJournal;
	}

	public BswUnitorg getBswUnitorgByIdUnitorgBayard() {
		return this.bswUnitorgByIdUnitorgBayard;
	}

	public void setBswUnitorgByIdUnitorgBayard(
			BswUnitorg bswUnitorgByIdUnitorgBayard) {
		this.bswUnitorgByIdUnitorgBayard = bswUnitorgByIdUnitorgBayard;
	}

	public BswUnitorg getBswUnitorgByIdUnitorgClient() {
		return this.bswUnitorgByIdUnitorgClient;
	}

	public void setBswUnitorgByIdUnitorgClient(
			BswUnitorg bswUnitorgByIdUnitorgClient) {
		this.bswUnitorgByIdUnitorgClient = bswUnitorgByIdUnitorgClient;
	}

	public BswPersonne getBswPersonneByIdResponsableAbonne() {
		return this.bswPersonneByIdResponsableAbonne;
	}

	public void setBswPersonneByIdResponsableAbonne(
			BswPersonne bswPersonneByIdResponsableAbonne) {
		this.bswPersonneByIdResponsableAbonne = bswPersonneByIdResponsableAbonne;
	}

	public BswPersonne getBswPersonneByIdResponsable() {
		return this.bswPersonneByIdResponsable;
	}

	public void setBswPersonneByIdResponsable(
			BswPersonne bswPersonneByIdResponsable) {
		this.bswPersonneByIdResponsable = bswPersonneByIdResponsable;
	}

	public BswSousFamille getBswSousFamille() {
		return this.bswSousFamille;
	}

	public void setBswSousFamille(BswSousFamille bswSousFamille) {
		this.bswSousFamille = bswSousFamille;
	}

	public BswUnitorg getBswUnitorgByIdUnitorgImprimeur() {
		return this.bswUnitorgByIdUnitorgImprimeur;
	}

	public void setBswUnitorgByIdUnitorgImprimeur(
			BswUnitorg bswUnitorgByIdUnitorgImprimeur) {
		this.bswUnitorgByIdUnitorgImprimeur = bswUnitorgByIdUnitorgImprimeur;
	}

	public BswPersonne getBswPersonneByIdReferent() {
		return this.bswPersonneByIdReferent;
	}

	public void setBswPersonneByIdReferent(BswPersonne bswPersonneByIdReferent) {
		this.bswPersonneByIdReferent = bswPersonneByIdReferent;
	}

	public BswFamille getBswFamille() {
		return this.bswFamille;
	}

	public void setBswFamille(BswFamille bswFamille) {
		this.bswFamille = bswFamille;
	}

	public String getTitre() {
		return this.titre;
	}

	public void setTitre(String titre) {
		this.titre = titre;
	}

	public String getSousTitre() {
		return this.sousTitre;
	}

	public void setSousTitre(String sousTitre) {
		this.sousTitre = sousTitre;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getLieu() {
		return this.lieu;
	}

	public void setLieu(String lieu) {
		this.lieu = lieu;
	}

	public Integer getNbParutions() {
		return this.nbParutions;
	}

	public void setNbParutions(Integer nbParutions) {
		this.nbParutions = nbParutions;
	}

	public Integer getNbPages() {
		return this.nbPages;
	}

	public void setNbPages(Integer nbPages) {
		this.nbPages = nbPages;
	}

	public Boolean getFondCommun() {
		return this.fondCommun;
	}

	public void setFondCommun(Boolean fondCommun) {
		this.fondCommun = fondCommun;
	}

	public String getCommentaire() {
		return this.commentaire;
	}

	public void setCommentaire(String commentaire) {
		this.commentaire = commentaire;
	}

	public Boolean getAbonnementOuvert() {
		return this.abonnementOuvert;
	}

	public void setAbonnementOuvert(Boolean abonnementOuvert) {
		this.abonnementOuvert = abonnementOuvert;
	}

	public boolean isPaiementCb() {
		return this.paiementCb;
	}

	public void setPaiementCb(boolean paiementCb) {
		this.paiementCb = paiementCb;
	}

	public String getFormatFacture() {
		return this.formatFacture;
	}

	public void setFormatFacture(String formatFacture) {
		this.formatFacture = formatFacture;
	}

	public String getFormatClient() {
		return this.formatClient;
	}

	public void setFormatClient(String formatClient) {
		this.formatClient = formatClient;
	}

	public Date getDateCreation() {
		return this.dateCreation;
	}

	public void setDateCreation(Date dateCreation) {
		this.dateCreation = dateCreation;
	}

	public Date getDateModification() {
		return this.dateModification;
	}

	public void setDateModification(Date dateModification) {
		this.dateModification = dateModification;
	}

	public String getAuteurCreation() {
		return this.auteurCreation;
	}

	public void setAuteurCreation(String auteurCreation) {
		this.auteurCreation = auteurCreation;
	}

	public String getAuteurModification() {
		return this.auteurModification;
	}

	public void setAuteurModification(String auteurModification) {
		this.auteurModification = auteurModification;
	}

	public String getUrlApercuVignette() {
		return this.urlApercuVignette;
	}

	public void setUrlApercuVignette(String urlApercuVignette) {
		this.urlApercuVignette = urlApercuVignette;
	}

	public String getUrlPagePresentation() {
		return this.urlPagePresentation;
	}

	public void setUrlPagePresentation(String urlPagePresentation) {
		this.urlPagePresentation = urlPagePresentation;
	}

	public String getLocalite() {
		return this.localite;
	}

	public void setLocalite(String localite) {
		this.localite = localite;
	}

	public String getSequencePagination() {
		return this.sequencePagination;
	}

	public void setSequencePagination(String sequencePagination) {
		this.sequencePagination = sequencePagination;
	}

	public String getReference() {
		return this.reference;
	}

	public void setReference(String reference) {
		this.reference = reference;
	}

	public Boolean getFusionDesUrs() {
		return this.fusionDesUrs;
	}

	public void setFusionDesUrs(Boolean fusionDesUrs) {
		this.fusionDesUrs = fusionDesUrs;
	}

	public String getSiteGeneBase() {
		return this.siteGeneBase;
	}

	public void setSiteGeneBase(String siteGeneBase) {
		this.siteGeneBase = siteGeneBase;
	}

	public String getSiteGeneUrl() {
		return this.siteGeneUrl;
	}

	public void setSiteGeneUrl(String siteGeneUrl) {
		this.siteGeneUrl = siteGeneUrl;
	}

	public String getSiteGeneLogin() {
		return this.siteGeneLogin;
	}

	public void setSiteGeneLogin(String siteGeneLogin) {
		this.siteGeneLogin = siteGeneLogin;
	}

	public String getSiteGeneMdp() {
		return this.siteGeneMdp;
	}

	public void setSiteGeneMdp(String siteGeneMdp) {
		this.siteGeneMdp = siteGeneMdp;
	}

	public boolean isMiseEnFormeEtendue() {
		return this.miseEnFormeEtendue;
	}

	public void setMiseEnFormeEtendue(boolean miseEnFormeEtendue) {
		this.miseEnFormeEtendue = miseEnFormeEtendue;
	}

	public Set<BswgaJournalHasAbonne> getBswgaJournalHasAbonnes() {
		return this.bswgaJournalHasAbonnes;
	}

	public void setBswgaJournalHasAbonnes(
			Set<BswgaJournalHasAbonne> bswgaJournalHasAbonnes) {
		this.bswgaJournalHasAbonnes = bswgaJournalHasAbonnes;
	}

	public Set<BswConfigurationPaiement> getBswConfigurationPaiements() {
		return this.bswConfigurationPaiements;
	}

	public void setBswConfigurationPaiements(
			Set<BswConfigurationPaiement> bswConfigurationPaiements) {
		this.bswConfigurationPaiements = bswConfigurationPaiements;
	}

	public Set<BswMultiSites> getBswMultiSiteses() {
		return this.bswMultiSiteses;
	}

	public void setBswMultiSiteses(Set<BswMultiSites> bswMultiSiteses) {
		this.bswMultiSiteses = bswMultiSiteses;
	}

	public Set<BswUnitorg> getBswUnitorgs() {
		return this.bswUnitorgs;
	}

	public void setBswUnitorgs(Set<BswUnitorg> bswUnitorgs) {
		this.bswUnitorgs = bswUnitorgs;
	}

	public Set<BswApplication> getBswApplications() {
		return this.bswApplications;
	}

	public void setBswApplications(Set<BswApplication> bswApplications) {
		this.bswApplications = bswApplications;
	}

	public Set<BswgaTypeAbonne> getBswgaTypeAbonnes() {
		return this.bswgaTypeAbonnes;
	}

	public void setBswgaTypeAbonnes(Set<BswgaTypeAbonne> bswgaTypeAbonnes) {
		this.bswgaTypeAbonnes = bswgaTypeAbonnes;
	}

	public Set<BswdtPage> getBswdtPages() {
		return this.bswdtPages;
	}

	public void setBswdtPages(Set<BswdtPage> bswdtPages) {
		this.bswdtPages = bswdtPages;
	}

	public Set<BswPersonne> getBswPersonnes() {
		return this.bswPersonnes;
	}

	public void setBswPersonnes(Set<BswPersonne> bswPersonnes) {
		this.bswPersonnes = bswPersonnes;
	}

	public Set<BswgaModeExpedition> getBswgaModeExpeditions() {
		return this.bswgaModeExpeditions;
	}

	public void setBswgaModeExpeditions(
			Set<BswgaModeExpedition> bswgaModeExpeditions) {
		this.bswgaModeExpeditions = bswgaModeExpeditions;
	}

	public Set<BswParution> getBswParutions() {
		return this.bswParutions;
	}

	public void setBswParutions(Set<BswParution> bswParutions) {
		this.bswParutions = bswParutions;
	}

	public Set<BswgaAbonnement> getBswgaAbonnements() {
		return this.bswgaAbonnements;
	}

	public void setBswgaAbonnements(Set<BswgaAbonnement> bswgaAbonnements) {
		this.bswgaAbonnements = bswgaAbonnements;
	}

	public Set<BswdtModelPage> getBswdtModelPages() {
		return this.bswdtModelPages;
	}

	public void setBswdtModelPages(Set<BswdtModelPage> bswdtModelPages) {
		this.bswdtModelPages = bswdtModelPages;
	}

	public Set<BswgaSecteur> getBswgaSecteurs() {
		return this.bswgaSecteurs;
	}

	public void setBswgaSecteurs(Set<BswgaSecteur> bswgaSecteurs) {
		this.bswgaSecteurs = bswgaSecteurs;
	}

	public Set<BswgaTarif> getBswgaTarifs() {
		return this.bswgaTarifs;
	}

	public void setBswgaTarifs(Set<BswgaTarif> bswgaTarifs) {
		this.bswgaTarifs = bswgaTarifs;
	}

	public Set<BswgaModele> getBswgaModeles() {
		return this.bswgaModeles;
	}

	public void setBswgaModeles(Set<BswgaModele> bswgaModeles) {
		this.bswgaModeles = bswgaModeles;
	}

	public Set<BswJournal> getBswJournalsForIdJournal() {
		return this.bswJournalsForIdJournal;
	}

	public void setBswJournalsForIdJournal(
			Set<BswJournal> bswJournalsForIdJournal) {
		this.bswJournalsForIdJournal = bswJournalsForIdJournal;
	}

	public Set<BswPersonne> getBswPersonnes_1() {
		return this.bswPersonnes_1;
	}

	public void setBswPersonnes_1(Set<BswPersonne> bswPersonnes_1) {
		this.bswPersonnes_1 = bswPersonnes_1;
	}

	public Set<BswJournal> getBswJournalsForIdJournalFondCommun() {
		return this.bswJournalsForIdJournalFondCommun;
	}

	public void setBswJournalsForIdJournalFondCommun(
			Set<BswJournal> bswJournalsForIdJournalFondCommun) {
		this.bswJournalsForIdJournalFondCommun = bswJournalsForIdJournalFondCommun;
	}

	public Set<BswSecteur> getBswSecteurs() {
		return this.bswSecteurs;
	}

	public void setBswSecteurs(Set<BswSecteur> bswSecteurs) {
		this.bswSecteurs = bswSecteurs;
	}

	public Set<BswDepartement> getBswDepartements() {
		return this.bswDepartements;
	}

	public void setBswDepartements(Set<BswDepartement> bswDepartements) {
		this.bswDepartements = bswDepartements;
	}

	@Override
	public String toString() {
		return "BswJournal [idJournal=" + idJournal + ", titre=" + titre + ", sousTitre=" + sousTitre + ", code=" + code
				+ ", lieu=" + lieu + ", nbParutions=" + nbParutions + ", nbPages=" + nbPages + ", fondCommun="
				+ fondCommun + ", commentaire=" + commentaire + ", abonnementOuvert=" + abonnementOuvert
				+ ", paiementCb=" + paiementCb + ", formatFacture=" + formatFacture + ", formatClient=" + formatClient
				+ ", dateCreation=" + dateCreation + ", dateModification=" + dateModification + ", auteurCreation="
				+ auteurCreation + ", auteurModification=" + auteurModification + ", urlApercuVignette="
				+ urlApercuVignette + ", urlPagePresentation=" + urlPagePresentation + ", localite=" + localite
				+ ", sequencePagination=" + sequencePagination + ", reference=" + reference + ", fusionDesUrs="
				+ fusionDesUrs + ", siteGeneBase=" + siteGeneBase + ", siteGeneUrl=" + siteGeneUrl + ", siteGeneLogin="
				+ siteGeneLogin + ", siteGeneMdp=" + siteGeneMdp + ", miseEnFormeEtendue=" + miseEnFormeEtendue + "]";
	}

}
