package com.gj.model;

// Generated 4 mars 2014 09:23:20 by Hibernate Tools 3.4.0.CR1

import java.util.Date;


/**
 * BswLog generated by hbm2java
 */
public class BswLog   {

	private Integer idLog;
	private String application;
	private String classe;
	private Integer refObjet;
	private String action;
	private String description;
	private Date date;
	private String auteur;

	public BswLog() {
	}

	public BswLog(String application, String classe, Integer refObjet,
			String action, String description, Date date, String auteur) {
		this.application = application;
		this.classe = classe;
		this.refObjet = refObjet;
		this.action = action;
		this.description = description;
		this.date = date;
		this.auteur = auteur;
	}

	public Integer getIdLog() {
		return this.idLog;
	}

	public void setIdLog(Integer idLog) {
		this.idLog = idLog;
	}

	public String getApplication() {
		return this.application;
	}

	public void setApplication(String application) {
		this.application = application;
	}

	public String getClasse() {
		return this.classe;
	}

	public void setClasse(String classe) {
		this.classe = classe;
	}

	public Integer getRefObjet() {
		return this.refObjet;
	}

	public void setRefObjet(Integer refObjet) {
		this.refObjet = refObjet;
	}

	public String getAction() {
		return this.action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public String getAuteur() {
		return this.auteur;
	}

	public void setAuteur(String auteur) {
		this.auteur = auteur;
	}

}
