package com.gj.model;

// Generated 4 mars 2014 09:23:20 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;


/**
 * BswMultiSites generated by hbm2java
 */
public class BswMultiSites   {

	private Integer idMultiSite;
	private BswJournal bswJournal;
	private String siteGeneUrl;
	private String siteGeneCategorie;
	private String siteGeneLogin;
	private String siteGeneMdp;
	private Set<BswPersonne> bswPersonnes = new HashSet<BswPersonne>(0);

	public BswMultiSites() {
	}

	public BswMultiSites(BswJournal bswJournal, String siteGeneUrl,
			String siteGeneCategorie, String siteGeneLogin, String siteGeneMdp,
			Set<BswPersonne> bswPersonnes) {
		this.bswJournal = bswJournal;
		this.siteGeneUrl = siteGeneUrl;
		this.siteGeneCategorie = siteGeneCategorie;
		this.siteGeneLogin = siteGeneLogin;
		this.siteGeneMdp = siteGeneMdp;
		this.bswPersonnes = bswPersonnes;
	}

	public Integer getIdMultiSite() {
		return this.idMultiSite;
	}

	public void setIdMultiSite(Integer idMultiSite) {
		this.idMultiSite = idMultiSite;
	}

	public BswJournal getBswJournal() {
		return this.bswJournal;
	}

	public void setBswJournal(BswJournal bswJournal) {
		this.bswJournal = bswJournal;
	}

	public String getSiteGeneUrl() {
		return this.siteGeneUrl;
	}

	public void setSiteGeneUrl(String siteGeneUrl) {
		this.siteGeneUrl = siteGeneUrl;
	}

	public String getSiteGeneCategorie() {
		return this.siteGeneCategorie;
	}

	public void setSiteGeneCategorie(String siteGeneCategorie) {
		this.siteGeneCategorie = siteGeneCategorie;
	}

	public String getSiteGeneLogin() {
		return this.siteGeneLogin;
	}

	public void setSiteGeneLogin(String siteGeneLogin) {
		this.siteGeneLogin = siteGeneLogin;
	}

	public String getSiteGeneMdp() {
		return this.siteGeneMdp;
	}

	public void setSiteGeneMdp(String siteGeneMdp) {
		this.siteGeneMdp = siteGeneMdp;
	}

	public Set<BswPersonne> getBswPersonnes() {
		return this.bswPersonnes;
	}

	public void setBswPersonnes(Set<BswPersonne> bswPersonnes) {
		this.bswPersonnes = bswPersonnes;
	}

}
