package com.gj.model;

// Generated 4 mars 2014 09:23:20 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;


/**
 * BswModePaiement generated by hbm2java
 */
public class BswModePaiement  {

	private Integer idModePaiement;
	private String abreviation;
	private String libelle;
	private String explications;
	private Set<BswConfigurationPaiement> bswConfigurationPaiements = new HashSet<BswConfigurationPaiement>(
			0);

	public BswModePaiement() {
	}

	public BswModePaiement(String abreviation, String libelle,
			String explications,
			Set<BswConfigurationPaiement> bswConfigurationPaiements) {
		this.abreviation = abreviation;
		this.libelle = libelle;
		this.explications = explications;
		this.bswConfigurationPaiements = bswConfigurationPaiements;
	}

	public Integer getIdModePaiement() {
		return this.idModePaiement;
	}

	public void setIdModePaiement(Integer idModePaiement) {
		this.idModePaiement = idModePaiement;
	}

	public String getAbreviation() {
		return this.abreviation;
	}

	public void setAbreviation(String abreviation) {
		this.abreviation = abreviation;
	}

	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	public String getExplications() {
		return this.explications;
	}

	public void setExplications(String explications) {
		this.explications = explications;
	}

	public Set<BswConfigurationPaiement> getBswConfigurationPaiements() {
		return this.bswConfigurationPaiements;
	}

	public void setBswConfigurationPaiements(
			Set<BswConfigurationPaiement> bswConfigurationPaiements) {
		this.bswConfigurationPaiements = bswConfigurationPaiements;
	}

}
