package com.gj.model;

// Generated 4 mars 2014 09:23:20 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * BswPersonne generated by hbm2java
 */
public class BswPersonne  {

	private Integer idPersonne;
	private Integer idPortalEntity;
	private String nom;
	private String prenom;
	private String nomNaissance;
	private Date dateNaissance;
	private String sexe;
	private String commentaire;
	private Date dateCreation;
	private Date dateModification;
	private String auteurCreation;
	private String auteurModification;
	private Set<BswgaSecteur> bswgaSecteurs = new HashSet<BswgaSecteur>(0);
	private Set<BswJournal> bswJournalsForIdResponsable = new HashSet<BswJournal>(
			0);
	private Set<BswFonction> bswFonctions = new HashSet<BswFonction>(0);
	private Set<BswdtForum> bswdtForums = new HashSet<BswdtForum>(0);
	private Set<BswJournal> bswJournalsForIdReferent = new HashSet<BswJournal>(
			0);
	private Set<BswJournal> bswJournals = new HashSet<BswJournal>(0);
	private Set<BswdtPage> bswdtPages = new HashSet<BswdtPage>(0);
	private Set<BswdtUniteRedactionnelle> bswdtUniteRedactionnelles = new HashSet<BswdtUniteRedactionnelle>(
			0);
	//private Set<BswMultiSites> bswMultiSiteses = new HashSet<BswMultiSites>(0);
	private Set<BswgaSecteur> bswgaSecteurs_1 = new HashSet<BswgaSecteur>(0);
	private Set<BswJournal> bswJournals_1 = new HashSet<BswJournal>(0);
	private Set<BswCoordonnee> bswCoordonnees = new HashSet<BswCoordonnee>(0);
	private Set<BswJournal> bswJournalsForIdResponsableAbonne = new HashSet<BswJournal>(
			0);

	public BswPersonne() {
	}

	public BswPersonne(Integer idPortalEntity, String nom, String prenom,
			String nomNaissance, Date dateNaissance, String sexe,
			String commentaire, Date dateCreation, Date dateModification,
			String auteurCreation, String auteurModification,
			Set<BswgaSecteur> bswgaSecteurs,
			Set<BswJournal> bswJournalsForIdResponsable,
			Set<BswFonction> bswFonctions, Set<BswdtForum> bswdtForums,
			Set<BswJournal> bswJournalsForIdReferent,
			Set<BswJournal> bswJournals, Set<BswdtPage> bswdtPages,
			Set<BswdtUniteRedactionnelle> bswdtUniteRedactionnelles,
			//Set<BswMultiSites> bswMultiSiteses,
			Set<BswgaSecteur> bswgaSecteurs_1, Set<BswJournal> bswJournals_1,
			Set<BswCoordonnee> bswCoordonnees,
			Set<BswJournal> bswJournalsForIdResponsableAbonne) {
		this.idPortalEntity = idPortalEntity;
		this.nom = nom;
		this.prenom = prenom;
		this.nomNaissance = nomNaissance;
		this.dateNaissance = dateNaissance;
		this.sexe = sexe;
		this.commentaire = commentaire;
		this.dateCreation = dateCreation;
		this.dateModification = dateModification;
		this.auteurCreation = auteurCreation;
		this.auteurModification = auteurModification;
		this.bswgaSecteurs = bswgaSecteurs;
		this.bswJournalsForIdResponsable = bswJournalsForIdResponsable;
		this.bswFonctions = bswFonctions;
		this.bswdtForums = bswdtForums;
		this.bswJournalsForIdReferent = bswJournalsForIdReferent;
		this.bswJournals = bswJournals;
		this.bswdtPages = bswdtPages;
		this.bswdtUniteRedactionnelles = bswdtUniteRedactionnelles;
	//	this.bswMultiSiteses = bswMultiSiteses;
		this.bswgaSecteurs_1 = bswgaSecteurs_1;
		this.bswJournals_1 = bswJournals_1;
		this.bswCoordonnees = bswCoordonnees;
		this.bswJournalsForIdResponsableAbonne = bswJournalsForIdResponsableAbonne;
	}

	public Integer getIdPersonne() {
		return this.idPersonne;
	}

	public void setIdPersonne(Integer idPersonne) {
		this.idPersonne = idPersonne;
	}

	public Integer getIdPortalEntity() {
		return this.idPortalEntity;
	}

	public void setIdPortalEntity(Integer idPortalEntity) {
		this.idPortalEntity = idPortalEntity;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	public String getNomNaissance() {
		return this.nomNaissance;
	}

	public void setNomNaissance(String nomNaissance) {
		this.nomNaissance = nomNaissance;
	}

	public Date getDateNaissance() {
		return this.dateNaissance;
	}

	public void setDateNaissance(Date dateNaissance) {
		this.dateNaissance = dateNaissance;
	}

	public String getSexe() {
		return this.sexe;
	}

	public void setSexe(String sexe) {
		this.sexe = sexe;
	}

	public String getCommentaire() {
		return this.commentaire;
	}

	public void setCommentaire(String commentaire) {
		this.commentaire = commentaire;
	}

	public Date getDateCreation() {
		return this.dateCreation;
	}

	public void setDateCreation(Date dateCreation) {
		this.dateCreation = dateCreation;
	}

	public Date getDateModification() {
		return this.dateModification;
	}

	public void setDateModification(Date dateModification) {
		this.dateModification = dateModification;
	}

	public String getAuteurCreation() {
		return this.auteurCreation;
	}

	public void setAuteurCreation(String auteurCreation) {
		this.auteurCreation = auteurCreation;
	}

	public String getAuteurModification() {
		return this.auteurModification;
	}

	public void setAuteurModification(String auteurModification) {
		this.auteurModification = auteurModification;
	}

	public Set<BswgaSecteur> getBswgaSecteurs() {
		return this.bswgaSecteurs;
	}

	public void setBswgaSecteurs(Set<BswgaSecteur> bswgaSecteurs) {
		this.bswgaSecteurs = bswgaSecteurs;
	}

	public Set<BswJournal> getBswJournalsForIdResponsable() {
		return this.bswJournalsForIdResponsable;
	}

	public void setBswJournalsForIdResponsable(
			Set<BswJournal> bswJournalsForIdResponsable) {
		this.bswJournalsForIdResponsable = bswJournalsForIdResponsable;
	}

	public Set<BswFonction> getBswFonctions() {
		return this.bswFonctions;
	}

	public void setBswFonctions(Set<BswFonction> bswFonctions) {
		this.bswFonctions = bswFonctions;
	}

	public Set<BswdtForum> getBswdtForums() {
		return this.bswdtForums;
	}

	public void setBswdtForums(Set<BswdtForum> bswdtForums) {
		this.bswdtForums = bswdtForums;
	}

	public Set<BswJournal> getBswJournalsForIdReferent() {
		return this.bswJournalsForIdReferent;
	}

	public void setBswJournalsForIdReferent(
			Set<BswJournal> bswJournalsForIdReferent) {
		this.bswJournalsForIdReferent = bswJournalsForIdReferent;
	}

	public Set<BswJournal> getBswJournals() {
		return this.bswJournals;
	}

	public void setBswJournals(Set<BswJournal> bswJournals) {
		this.bswJournals = bswJournals;
	}

	public Set<BswdtPage> getBswdtPages() {
		return this.bswdtPages;
	}

	public void setBswdtPages(Set<BswdtPage> bswdtPages) {
		this.bswdtPages = bswdtPages;
	}

	public Set<BswdtUniteRedactionnelle> getBswdtUniteRedactionnelles() {
		return this.bswdtUniteRedactionnelles;
	}

	public void setBswdtUniteRedactionnelles(
			Set<BswdtUniteRedactionnelle> bswdtUniteRedactionnelles) {
		this.bswdtUniteRedactionnelles = bswdtUniteRedactionnelles;
	}

	/*public Set<BswMultiSites> getBswMultiSiteses() {
		return this.bswMultiSiteses;
	}

	public void setBswMultiSiteses(Set<BswMultiSites> bswMultiSiteses) {
		this.bswMultiSiteses = bswMultiSiteses;
	}*/

	public Set<BswgaSecteur> getBswgaSecteurs_1() {
		return this.bswgaSecteurs_1;
	}

	public void setBswgaSecteurs_1(Set<BswgaSecteur> bswgaSecteurs_1) {
		this.bswgaSecteurs_1 = bswgaSecteurs_1;
	}

	public Set<BswJournal> getBswJournals_1() {
		return this.bswJournals_1;
	}

	public void setBswJournals_1(Set<BswJournal> bswJournals_1) {
		this.bswJournals_1 = bswJournals_1;
	}

	public Set<BswCoordonnee> getBswCoordonnees() {
		return this.bswCoordonnees;
	}

	public void setBswCoordonnees(Set<BswCoordonnee> bswCoordonnees) {
		this.bswCoordonnees = bswCoordonnees;
	}

	public Set<BswJournal> getBswJournalsForIdResponsableAbonne() {
		return this.bswJournalsForIdResponsableAbonne;
	}

	public void setBswJournalsForIdResponsableAbonne(
			Set<BswJournal> bswJournalsForIdResponsableAbonne) {
		this.bswJournalsForIdResponsableAbonne = bswJournalsForIdResponsableAbonne;
	}

	@Override
	public String toString() {
		return "BswPersonne [idPersonne=" + idPersonne + ", idPortalEntity=" + idPortalEntity + ", nom=" + nom
				+ ", prenom=" + prenom + ", nomNaissance=" + nomNaissance + ", dateNaissance=" + dateNaissance
				+ ", sexe=" + sexe + ", commentaire=" + commentaire + ", dateCreation=" + dateCreation
				+ ", dateModification=" + dateModification + ", auteurCreation=" + auteurCreation
				+ ", auteurModification=" + auteurModification + "]";
	}
	
}
