package com.gj.model;

// Generated 4 mars 2014 09:23:20 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;


/**
 * BswSecteur generated by hbm2java
 */
public class BswSecteur   {

	private Integer idSecteur;
	private String libelle;
	private Set<BswJournal> bswJournals = new HashSet<BswJournal>(0);

	public BswSecteur() {
	}

	public BswSecteur(String libelle, Set<BswJournal> bswJournals) {
		this.libelle = libelle;
		this.bswJournals = bswJournals;
	}

	public Integer getIdSecteur() {
		return this.idSecteur;
	}

	public void setIdSecteur(Integer idSecteur) {
		this.idSecteur = idSecteur;
	}

	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	public Set<BswJournal> getBswJournals() {
		return this.bswJournals;
	}

	public void setBswJournals(Set<BswJournal> bswJournals) {
		this.bswJournals = bswJournals;
	}

}
