package com.gj.model;

// Generated 4 mars 2014 09:23:20 by Hibernate Tools 3.4.0.CR1

import java.util.Date;


/**
 * BswTransaction generated by hbm2java
 */
public class BswTransaction   {

	private Integer idTransaction;
	private boolean reabonnement;
	private Integer nbExemplaires;
	private Integer numeroDebut;
	private String montant;
	private int idStatut;
	private String statut;
	private Date date;
	private String refBanque;
	private Integer idUnitorg;
	private Integer idJournal;
	private Integer idAbonne;
	private Integer idAbonnement;
	private Integer idTarif;
	private Integer idModePaiement;
	private Integer idReferenceSystemeBancaire;
	private String log;
	private String nom;
	private String prenom;
	private String login;
	private String mdp;
	private Integer idCivilite;
	private Integer idPays;
	private String societe;
	private String tel;
	private String fax;
	private String mobile;
	private String email;
	private String siteWeb;
	private String destinataire;
	private String destinataireComplement;
	private String adresseLigne1;
	private String adresseLigne3;
	private String numeroVoie;
	private String libelleVoie;
	private String codePostal;
	private String ville;
	private String cedex;
	private String typeAdressePostale;

	public BswTransaction() {
	}

	public BswTransaction(boolean reabonnement, int idStatut) {
		this.reabonnement = reabonnement;
		this.idStatut = idStatut;
	}

	public BswTransaction(boolean reabonnement, Integer nbExemplaires,
			Integer numeroDebut, String montant, int idStatut, String statut,
			Date date, String refBanque, Integer idUnitorg, Integer idJournal,
			Integer idAbonne, Integer idAbonnement, Integer idTarif,
			Integer idModePaiement, Integer idReferenceSystemeBancaire,
			String log, String nom, String prenom, String login, String mdp,
			Integer idCivilite, Integer idPays, String societe, String tel,
			String fax, String mobile, String email, String siteWeb,
			String destinataire, String destinataireComplement,
			String adresseLigne1, String adresseLigne3, String numeroVoie,
			String libelleVoie, String codePostal, String ville, String cedex,
			String typeAdressePostale) {
		this.reabonnement = reabonnement;
		this.nbExemplaires = nbExemplaires;
		this.numeroDebut = numeroDebut;
		this.montant = montant;
		this.idStatut = idStatut;
		this.statut = statut;
		this.date = date;
		this.refBanque = refBanque;
		this.idUnitorg = idUnitorg;
		this.idJournal = idJournal;
		this.idAbonne = idAbonne;
		this.idAbonnement = idAbonnement;
		this.idTarif = idTarif;
		this.idModePaiement = idModePaiement;
		this.idReferenceSystemeBancaire = idReferenceSystemeBancaire;
		this.log = log;
		this.nom = nom;
		this.prenom = prenom;
		this.login = login;
		this.mdp = mdp;
		this.idCivilite = idCivilite;
		this.idPays = idPays;
		this.societe = societe;
		this.tel = tel;
		this.fax = fax;
		this.mobile = mobile;
		this.email = email;
		this.siteWeb = siteWeb;
		this.destinataire = destinataire;
		this.destinataireComplement = destinataireComplement;
		this.adresseLigne1 = adresseLigne1;
		this.adresseLigne3 = adresseLigne3;
		this.numeroVoie = numeroVoie;
		this.libelleVoie = libelleVoie;
		this.codePostal = codePostal;
		this.ville = ville;
		this.cedex = cedex;
		this.typeAdressePostale = typeAdressePostale;
	}

	public Integer getIdTransaction() {
		return this.idTransaction;
	}

	public void setIdTransaction(Integer idTransaction) {
		this.idTransaction = idTransaction;
	}

	public boolean isReabonnement() {
		return this.reabonnement;
	}

	public void setReabonnement(boolean reabonnement) {
		this.reabonnement = reabonnement;
	}

	public Integer getNbExemplaires() {
		return this.nbExemplaires;
	}

	public void setNbExemplaires(Integer nbExemplaires) {
		this.nbExemplaires = nbExemplaires;
	}

	public Integer getNumeroDebut() {
		return this.numeroDebut;
	}

	public void setNumeroDebut(Integer numeroDebut) {
		this.numeroDebut = numeroDebut;
	}

	public String getMontant() {
		return this.montant;
	}

	public void setMontant(String montant) {
		this.montant = montant;
	}

	public int getIdStatut() {
		return this.idStatut;
	}

	public void setIdStatut(int idStatut) {
		this.idStatut = idStatut;
	}

	public String getStatut() {
		return this.statut;
	}

	public void setStatut(String statut) {
		this.statut = statut;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public String getRefBanque() {
		return this.refBanque;
	}

	public void setRefBanque(String refBanque) {
		this.refBanque = refBanque;
	}

	public Integer getIdUnitorg() {
		return this.idUnitorg;
	}

	public void setIdUnitorg(Integer idUnitorg) {
		this.idUnitorg = idUnitorg;
	}

	public Integer getIdJournal() {
		return this.idJournal;
	}

	public void setIdJournal(Integer idJournal) {
		this.idJournal = idJournal;
	}

	public Integer getIdAbonne() {
		return this.idAbonne;
	}

	public void setIdAbonne(Integer idAbonne) {
		this.idAbonne = idAbonne;
	}

	public Integer getIdAbonnement() {
		return this.idAbonnement;
	}

	public void setIdAbonnement(Integer idAbonnement) {
		this.idAbonnement = idAbonnement;
	}

	public Integer getIdTarif() {
		return this.idTarif;
	}

	public void setIdTarif(Integer idTarif) {
		this.idTarif = idTarif;
	}

	public Integer getIdModePaiement() {
		return this.idModePaiement;
	}

	public void setIdModePaiement(Integer idModePaiement) {
		this.idModePaiement = idModePaiement;
	}

	public Integer getIdReferenceSystemeBancaire() {
		return this.idReferenceSystemeBancaire;
	}

	public void setIdReferenceSystemeBancaire(Integer idReferenceSystemeBancaire) {
		this.idReferenceSystemeBancaire = idReferenceSystemeBancaire;
	}

	public String getLog() {
		return this.log;
	}

	public void setLog(String log) {
		this.log = log;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getMdp() {
		return this.mdp;
	}

	public void setMdp(String mdp) {
		this.mdp = mdp;
	}

	public Integer getIdCivilite() {
		return this.idCivilite;
	}

	public void setIdCivilite(Integer idCivilite) {
		this.idCivilite = idCivilite;
	}

	public Integer getIdPays() {
		return this.idPays;
	}

	public void setIdPays(Integer idPays) {
		this.idPays = idPays;
	}

	public String getSociete() {
		return this.societe;
	}

	public void setSociete(String societe) {
		this.societe = societe;
	}

	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getSiteWeb() {
		return this.siteWeb;
	}

	public void setSiteWeb(String siteWeb) {
		this.siteWeb = siteWeb;
	}

	public String getDestinataire() {
		return this.destinataire;
	}

	public void setDestinataire(String destinataire) {
		this.destinataire = destinataire;
	}

	public String getDestinataireComplement() {
		return this.destinataireComplement;
	}

	public void setDestinataireComplement(String destinataireComplement) {
		this.destinataireComplement = destinataireComplement;
	}

	public String getAdresseLigne1() {
		return this.adresseLigne1;
	}

	public void setAdresseLigne1(String adresseLigne1) {
		this.adresseLigne1 = adresseLigne1;
	}

	public String getAdresseLigne3() {
		return this.adresseLigne3;
	}

	public void setAdresseLigne3(String adresseLigne3) {
		this.adresseLigne3 = adresseLigne3;
	}

	public String getNumeroVoie() {
		return this.numeroVoie;
	}

	public void setNumeroVoie(String numeroVoie) {
		this.numeroVoie = numeroVoie;
	}

	public String getLibelleVoie() {
		return this.libelleVoie;
	}

	public void setLibelleVoie(String libelleVoie) {
		this.libelleVoie = libelleVoie;
	}

	public String getCodePostal() {
		return this.codePostal;
	}

	public void setCodePostal(String codePostal) {
		this.codePostal = codePostal;
	}

	public String getVille() {
		return this.ville;
	}

	public void setVille(String ville) {
		this.ville = ville;
	}

	public String getCedex() {
		return this.cedex;
	}

	public void setCedex(String cedex) {
		this.cedex = cedex;
	}

	public String getTypeAdressePostale() {
		return this.typeAdressePostale;
	}

	public void setTypeAdressePostale(String typeAdressePostale) {
		this.typeAdressePostale = typeAdressePostale;
	}

}
