package com.gj.model;

// Generated 4 mars 2014 09:23:20 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import org.codehaus.jackson.annotate.JsonIgnore;
import org.codehaus.jackson.map.annotate.JsonView;

import java.io.Serializable;

/**
 * BswUnitorg generated by hbm2java
 */
public class BswUnitorg implements Serializable {

	@JsonView
	private Integer idUnitorg;
	@JsonView
	private BswTypeUnitorg bswTypeUnitorg;
	@JsonView
	private Integer idPortalEntity;
	@JsonView
	private String nom;
	@JsonView
	private String description;
	@JsonView
	private String reference;
	@JsonView
	private boolean frontOfficeActif;
	@JsonView
	private Date dateCreation;
	@JsonView
	private Date dateModification;
	@JsonView
	private String auteurCreation;
	@JsonView
	private String auteurModification;
	@JsonView
	private String urlLogoBandeau;
	@JsonView
	private String titreBandeau;
	@JsonView
	private String sousTitreBandeau;
	@JsonIgnore
	private Set<BswUnitorg> bswUnitorgsForIdUnitorgFils = new HashSet<BswUnitorg>(
			0);
	@JsonIgnore
	private Set<BswJournal> bswJournalsForIdUnitorgClient = new HashSet<BswJournal>(
			0);
	@JsonIgnore
	private Set<BswJournal> bswJournals = new HashSet<BswJournal>(0);
	@JsonIgnore
	private Set<BswJournal> bswJournalsForIdUnitorgImprimeur = new HashSet<BswJournal>(
			0);
	@JsonView
	private Set<BswCoordonnee> bswCoordonnees = new HashSet<BswCoordonnee>(0);
	@JsonIgnore
	private Set<BswFonction> bswFonctions = new HashSet<BswFonction>(0);
	@JsonIgnore
	private Set<BswUnitorg> bswUnitorgsForIdUnitorgPere = new HashSet<BswUnitorg>(
			0);
	@JsonIgnore
	private Set<BswJournal> bswJournalsForIdUnitorgBayard = new HashSet<BswJournal>(
			0);

	public BswUnitorg() {
	}

	public BswUnitorg(boolean frontOfficeActif) {
		this.frontOfficeActif = frontOfficeActif;
	}

	public BswUnitorg(BswTypeUnitorg bswTypeUnitorg, Integer idPortalEntity,
			String nom, String description, String reference,
			boolean frontOfficeActif, Date dateCreation, Date dateModification,
			String auteurCreation, String auteurModification,
			String urlLogoBandeau, String titreBandeau,
			String sousTitreBandeau,
			Set<BswUnitorg> bswUnitorgsForIdUnitorgFils,
			Set<BswJournal> bswJournalsForIdUnitorgClient,
			Set<BswJournal> bswJournals,
			Set<BswJournal> bswJournalsForIdUnitorgImprimeur,
			Set<BswCoordonnee> bswCoordonnees, Set<BswFonction> bswFonctions,
			Set<BswUnitorg> bswUnitorgsForIdUnitorgPere,
			Set<BswJournal> bswJournalsForIdUnitorgBayard) {
		this.bswTypeUnitorg = bswTypeUnitorg;
		this.idPortalEntity = idPortalEntity;
		this.nom = nom;
		this.description = description;
		this.reference = reference;
		this.frontOfficeActif = frontOfficeActif;
		this.dateCreation = dateCreation;
		this.dateModification = dateModification;
		this.auteurCreation = auteurCreation;
		this.auteurModification = auteurModification;
		this.urlLogoBandeau = urlLogoBandeau;
		this.titreBandeau = titreBandeau;
		this.sousTitreBandeau = sousTitreBandeau;
		this.bswUnitorgsForIdUnitorgFils = bswUnitorgsForIdUnitorgFils;
		this.bswJournalsForIdUnitorgClient = bswJournalsForIdUnitorgClient;
		this.bswJournals = bswJournals;
		this.bswJournalsForIdUnitorgImprimeur = bswJournalsForIdUnitorgImprimeur;
		this.bswCoordonnees = bswCoordonnees;
		this.bswFonctions = bswFonctions;
		this.bswUnitorgsForIdUnitorgPere = bswUnitorgsForIdUnitorgPere;
		this.bswJournalsForIdUnitorgBayard = bswJournalsForIdUnitorgBayard;
	}

	public Integer getIdUnitorg() {
		return this.idUnitorg;
	}

	public void setIdUnitorg(Integer idUnitorg) {
		this.idUnitorg = idUnitorg;
	}

	public BswTypeUnitorg getBswTypeUnitorg() {
		return this.bswTypeUnitorg;
	}

	public void setBswTypeUnitorg(BswTypeUnitorg bswTypeUnitorg) {
		this.bswTypeUnitorg = bswTypeUnitorg;
	}

	public Integer getIdPortalEntity() {
		return this.idPortalEntity;
	}

	public void setIdPortalEntity(Integer idPortalEntity) {
		this.idPortalEntity = idPortalEntity;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getReference() {
		return this.reference;
	}

	public void setReference(String reference) {
		this.reference = reference;
	}

	public boolean isFrontOfficeActif() {
		return this.frontOfficeActif;
	}

	public void setFrontOfficeActif(boolean frontOfficeActif) {
		this.frontOfficeActif = frontOfficeActif;
	}

	public Date getDateCreation() {
		return this.dateCreation;
	}

	public void setDateCreation(Date dateCreation) {
		this.dateCreation = dateCreation;
	}

	public Date getDateModification() {
		return this.dateModification;
	}

	public void setDateModification(Date dateModification) {
		this.dateModification = dateModification;
	}

	public String getAuteurCreation() {
		return this.auteurCreation;
	}

	public void setAuteurCreation(String auteurCreation) {
		this.auteurCreation = auteurCreation;
	}

	public String getAuteurModification() {
		return this.auteurModification;
	}

	public void setAuteurModification(String auteurModification) {
		this.auteurModification = auteurModification;
	}

	public String getUrlLogoBandeau() {
		return this.urlLogoBandeau;
	}

	public void setUrlLogoBandeau(String urlLogoBandeau) {
		this.urlLogoBandeau = urlLogoBandeau;
	}

	public String getTitreBandeau() {
		return this.titreBandeau;
	}

	public void setTitreBandeau(String titreBandeau) {
		this.titreBandeau = titreBandeau;
	}

	public String getSousTitreBandeau() {
		return this.sousTitreBandeau;
	}

	public void setSousTitreBandeau(String sousTitreBandeau) {
		this.sousTitreBandeau = sousTitreBandeau;
	}

	public Set<BswUnitorg> getBswUnitorgsForIdUnitorgFils() {
		return this.bswUnitorgsForIdUnitorgFils;
	}

	public void setBswUnitorgsForIdUnitorgFils(
			Set<BswUnitorg> bswUnitorgsForIdUnitorgFils) {
		this.bswUnitorgsForIdUnitorgFils = bswUnitorgsForIdUnitorgFils;
	}

	public Set<BswJournal> getBswJournalsForIdUnitorgClient() {
		return this.bswJournalsForIdUnitorgClient;
	}

	public void setBswJournalsForIdUnitorgClient(
			Set<BswJournal> bswJournalsForIdUnitorgClient) {
		this.bswJournalsForIdUnitorgClient = bswJournalsForIdUnitorgClient;
	}

	public Set<BswJournal> getBswJournals() {
		return this.bswJournals;
	}

	public void setBswJournals(Set<BswJournal> bswJournals) {
		this.bswJournals = bswJournals;
	}

	public Set<BswJournal> getBswJournalsForIdUnitorgImprimeur() {
		return this.bswJournalsForIdUnitorgImprimeur;
	}

	public void setBswJournalsForIdUnitorgImprimeur(
			Set<BswJournal> bswJournalsForIdUnitorgImprimeur) {
		this.bswJournalsForIdUnitorgImprimeur = bswJournalsForIdUnitorgImprimeur;
	}

	public Set<BswCoordonnee> getBswCoordonnees() {
		return this.bswCoordonnees;
	}

	public void setBswCoordonnees(Set<BswCoordonnee> bswCoordonnees) {
		this.bswCoordonnees = bswCoordonnees;
	}

	public Set<BswFonction> getBswFonctions() {
		return this.bswFonctions;
	}

	public void setBswFonctions(Set<BswFonction> bswFonctions) {
		this.bswFonctions = bswFonctions;
	}

	public Set<BswUnitorg> getBswUnitorgsForIdUnitorgPere() {
		return this.bswUnitorgsForIdUnitorgPere;
	}

	public void setBswUnitorgsForIdUnitorgPere(
			Set<BswUnitorg> bswUnitorgsForIdUnitorgPere) {
		this.bswUnitorgsForIdUnitorgPere = bswUnitorgsForIdUnitorgPere;
	}

	public Set<BswJournal> getBswJournalsForIdUnitorgBayard() {
		return this.bswJournalsForIdUnitorgBayard;
	}

	public void setBswJournalsForIdUnitorgBayard(
			Set<BswJournal> bswJournalsForIdUnitorgBayard) {
		this.bswJournalsForIdUnitorgBayard = bswJournalsForIdUnitorgBayard;
	}

}
